package residentsearch

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"testing"
	"time"

	chess "github.com/corentings/chess/v2"
)

// The corpus is generated by scripts/engine_parity_corpus.py from
// backend-python/chess_ai.py (_search at a fixed depth, level-100 settings
// without randomness, noise or clock). CI regenerates it with --check.
type pythonSearchCorpus struct {
	PythonChess string `json:"python_chess"`
	Positions   []struct {
		FEN   string          `json:"fen"`
		Depth int             `json:"depth"`
		Score json.RawMessage `json:"score"`
		Move  string          `json:"move"`
	} `json:"positions"`
}

func decodeScore(raw json.RawMessage) (float64, error) {
	var text string
	if err := json.Unmarshal(raw, &text); err == nil {
		switch text {
		case "inf":
			return math.Inf(1), nil
		case "-inf":
			return math.Inf(-1), nil
		}
		return 0, fmt.Errorf("unexpected score %q", text)
	}
	var value float64
	err := json.Unmarshal(raw, &value)
	return value, err
}

func sameScore(a, b float64) bool {
	if math.IsInf(a, 0) || math.IsInf(b, 0) {
		return a == b
	}
	return math.Abs(a-b) <= 1e-9*math.Max(1, math.Abs(b))
}

func TestAnalyzeFENMatchesPythonSearchCorpus(t *testing.T) {
	if testing.Short() {
		t.Skip("search parity corpus is slow; run without -short")
	}
	data, err := os.ReadFile("testdata/python_search_corpus.json")
	if err != nil {
		t.Fatal(err)
	}
	var corpus pythonSearchCorpus
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatal(err)
	}
	if len(corpus.Positions) < 100 {
		t.Fatalf("corpus too small: %d positions", len(corpus.Positions))
	}
	failures := 0
	tieBreaks := 0
	for _, position := range corpus.Positions {
		want, err := decodeScore(position.Score)
		if err != nil {
			t.Fatalf("%s: %v", position.FEN, err)
		}
		snapshot, err := New().AnalyzeFEN(context.Background(), position.FEN, position.Depth, time.Hour)
		if err != nil || len(snapshot.Candidates) == 0 {
			t.Errorf("%s: candidates=%d err=%v", position.FEN, len(snapshot.Candidates), err)
			failures++
			continue
		}
		best := snapshot.Candidates[0].Score
		if !sameScore(best, want) {
			failures++
			if failures <= 20 {
				t.Errorf("depth %d %s: go value=%v python value=%v", position.Depth, position.FEN, best, want)
			}
			continue
		}
		// Python's move must be one of Go's equally best moves.
		pythonMoveIsBest := false
		for _, candidate := range snapshot.Candidates {
			if candidate.UCI == position.Move {
				pythonMoveIsBest = sameScore(candidate.Score, best)
				break
			}
		}
		if !pythonMoveIsBest {
			failures++
			if failures <= 20 {
				t.Errorf("depth %d %s: python move %s is not among go's best (go chose %s)",
					position.Depth, position.FEN, position.Move, snapshot.Candidates[0].UCI)
			}
			continue
		}
		if snapshot.Candidates[0].UCI != position.Move {
			tieBreaks++
		}
	}
	if failures > 0 {
		t.Fatalf("%d/%d positions differ from Python (python-chess %s)", failures, len(corpus.Positions), corpus.PythonChess)
	}
	t.Logf("%d positions match; %d break a tie between equally best moves differently", len(corpus.Positions), tieBreaks)
}

// History parity: scripts/engine_history_parity_corpus.py searches boards that
// carry the game's move stack, where earlier repetitions turn lines into
// draws. AnalyzeGame must agree with Python there, and the corpus must hold
// positions where the history actually changes the value.
func TestAnalyzeGameMatchesPythonHistoryCorpus(t *testing.T) {
	data, err := os.ReadFile("testdata/python_history_corpus.json")
	if err != nil {
		t.Fatal(err)
	}
	var corpus struct {
		HistorySensitive int `json:"historySensitive"`
		Positions        []struct {
			Moves        []string        `json:"moves"`
			FEN          string          `json:"fen"`
			Depth        int             `json:"depth"`
			Score        json.RawMessage `json:"score"`
			Move         string          `json:"move"`
			FENOnlyScore json.RawMessage `json:"fenOnlyScore"`
		} `json:"positions"`
	}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatal(err)
	}
	if len(corpus.Positions) < 50 || corpus.HistorySensitive < 3 {
		t.Fatalf("corpus too weak: %d positions, %d history-sensitive", len(corpus.Positions), corpus.HistorySensitive)
	}
	failures := 0
	for _, position := range corpus.Positions {
		positions, err := replayUCI(position.Moves)
		if err != nil {
			t.Fatalf("%v: %v", position.Moves, err)
		}
		want, err := decodeScore(position.Score)
		if err != nil {
			t.Fatal(err)
		}
		snapshot, err := New().AnalyzeGame(context.Background(), positions, position.Depth, time.Hour)
		if err != nil || len(snapshot.Candidates) == 0 {
			t.Errorf("%v: candidates=%d err=%v", position.Moves, len(snapshot.Candidates), err)
			failures++
			continue
		}
		best := snapshot.Candidates[0].Score
		if !sameScore(best, want) {
			failures++
			if failures <= 20 {
				fenOnly, _ := decodeScore(position.FENOnlyScore)
				t.Errorf("depth %d %v: go=%v python=%v (fen-only python=%v)", position.Depth, position.Moves, best, want, fenOnly)
			}
			continue
		}
		pythonMoveIsBest := false
		for _, candidate := range snapshot.Candidates {
			if candidate.UCI == position.Move {
				pythonMoveIsBest = sameScore(candidate.Score, best)
				break
			}
		}
		if !pythonMoveIsBest {
			failures++
			if failures <= 20 {
				t.Errorf("depth %d %v: python move %s not among go's best", position.Depth, position.Moves, position.Move)
			}
		}
	}
	if failures > 0 {
		t.Fatalf("%d/%d history positions differ from Python", failures, len(corpus.Positions))
	}
}

func replayUCI(moves []string) ([]*chess.Position, error) {
	game := chess.NewGame()
	positions := []*chess.Position{game.Position()}
	for _, uci := range moves {
		move, err := chess.UCINotation{}.Decode(game.Position(), uci)
		if err != nil {
			return nil, err
		}
		if err := game.Move(move, nil); err != nil {
			return nil, err
		}
		positions = append(positions, game.Position())
	}
	return positions, nil
}
