package residentsearch

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"testing"
	"time"
)

// The corpus is generated by scripts/engine_parity_corpus.py from
// backend-python/chess_ai.py (_search at a fixed depth, level-100 settings
// without randomness, noise or clock). CI regenerates it with --check.
type pythonSearchCorpus struct {
	PythonChess string `json:"python_chess"`
	Positions   []struct {
		FEN   string          `json:"fen"`
		Depth int             `json:"depth"`
		Score json.RawMessage `json:"score"`
		Move  string          `json:"move"`
	} `json:"positions"`
}

func decodeScore(raw json.RawMessage) (float64, error) {
	var text string
	if err := json.Unmarshal(raw, &text); err == nil {
		switch text {
		case "inf":
			return math.Inf(1), nil
		case "-inf":
			return math.Inf(-1), nil
		}
		return 0, fmt.Errorf("unexpected score %q", text)
	}
	var value float64
	err := json.Unmarshal(raw, &value)
	return value, err
}

func sameScore(a, b float64) bool {
	if math.IsInf(a, 0) || math.IsInf(b, 0) {
		return a == b
	}
	return math.Abs(a-b) <= 1e-9*math.Max(1, math.Abs(b))
}

func TestAnalyzeFENMatchesPythonSearchCorpus(t *testing.T) {
	if testing.Short() {
		t.Skip("search parity corpus is slow; run without -short")
	}
	data, err := os.ReadFile("testdata/python_search_corpus.json")
	if err != nil {
		t.Fatal(err)
	}
	var corpus pythonSearchCorpus
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatal(err)
	}
	if len(corpus.Positions) < 100 {
		t.Fatalf("corpus too small: %d positions", len(corpus.Positions))
	}
	failures := 0
	tieBreaks := 0
	for _, position := range corpus.Positions {
		want, err := decodeScore(position.Score)
		if err != nil {
			t.Fatalf("%s: %v", position.FEN, err)
		}
		snapshot, err := New().AnalyzeFEN(context.Background(), position.FEN, position.Depth, time.Hour)
		if err != nil || len(snapshot.Candidates) == 0 {
			t.Errorf("%s: candidates=%d err=%v", position.FEN, len(snapshot.Candidates), err)
			failures++
			continue
		}
		best := snapshot.Candidates[0].Score
		if !sameScore(best, want) {
			failures++
			if failures <= 20 {
				t.Errorf("depth %d %s: go value=%v python value=%v", position.Depth, position.FEN, best, want)
			}
			continue
		}
		// Python's move must be one of Go's equally best moves.
		pythonMoveIsBest := false
		for _, candidate := range snapshot.Candidates {
			if candidate.UCI == position.Move {
				pythonMoveIsBest = sameScore(candidate.Score, best)
				break
			}
		}
		if !pythonMoveIsBest {
			failures++
			if failures <= 20 {
				t.Errorf("depth %d %s: python move %s is not among go's best (go chose %s)",
					position.Depth, position.FEN, position.Move, snapshot.Candidates[0].UCI)
			}
			continue
		}
		if snapshot.Candidates[0].UCI != position.Move {
			tieBreaks++
		}
	}
	if failures > 0 {
		t.Fatalf("%d/%d positions differ from Python (python-chess %s)", failures, len(corpus.Positions), corpus.PythonChess)
	}
	t.Logf("%d positions match; %d break a tie between equally best moves differently", len(corpus.Positions), tieBreaks)
}
