package residentsearch

import (
	"context"
	"encoding/json"
	"os"
	"slices"
	"testing"
	"time"

	chess "github.com/corentings/chess/v2"
)

// The corpus is generated by scripts/engine_pv_parity_corpus.py from
// backend-python/engine_analysis.py: every root candidate's score, immediate
// reply and proven line at a fixed depth, plus principal_variation.
type pvCorpus struct {
	Positions []struct {
		FEN        string `json:"fen"`
		Depth      int    `json:"depth"`
		Candidates []struct {
			Move  string          `json:"move"`
			Score json.RawMessage `json:"score"`
			Reply string          `json:"reply"`
			PV    []string        `json:"pv"`
		} `json:"candidates"`
		Principal *struct {
			Moves          []string        `json:"moves"`
			Score          json.RawMessage `json:"score"`
			Depth          int             `json:"depth"`
			CandidateCount int             `json:"candidateCount"`
		} `json:"principal"`
	} `json:"positions"`
}

func TestPrincipalVariationMatchesPythonCorpus(t *testing.T) {
	if testing.Short() {
		t.Skip("principal variation corpus is slow; run without -short")
	}
	data, err := os.ReadFile("testdata/python_pv_corpus.json")
	if err != nil {
		t.Fatal(err)
	}
	var corpus pvCorpus
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatal(err)
	}
	if len(corpus.Positions) < 40 {
		t.Fatalf("corpus too small: %d", len(corpus.Positions))
	}
	scoreDiffs, replyDiffs, pvDiffs, principalDiffs, compared := 0, 0, 0, 0, 0
	for _, position := range corpus.Positions {
		option, err := chess.FEN(position.FEN)
		if err != nil {
			t.Fatal(err)
		}
		root := chess.NewGame(option).Position()
		snapshot, err := New().AnalyzeGame(context.Background(), []*chess.Position{root}, position.Depth, time.Hour)
		if err != nil {
			t.Fatalf("%s: %v", position.FEN, err)
		}
		byMove := map[string]Candidate{}
		for _, c := range snapshot.Candidates {
			byMove[c.UCI] = c
		}
		for _, want := range position.Candidates {
			got, ok := byMove[want.Move]
			if !ok {
				t.Fatalf("%s: go lacks candidate %s", position.FEN, want.Move)
			}
			compared++
			score, _ := decodeScore(want.Score)
			if !sameScore(got.Score, score) {
				scoreDiffs++
				continue
			}
			if got.Reply != want.Reply {
				replyDiffs++
			}
			if !slices.Equal(got.PV, want.PV) {
				pvDiffs++
			}
		}
		pv, err := New().PrincipalVariation(context.Background(), []*chess.Position{root}, position.Depth, time.Hour)
		if err != nil {
			t.Fatal(err)
		}
		if (pv == nil) != (position.Principal == nil) {
			t.Fatalf("%s: principal presence differs", position.FEN)
		}
		if pv != nil && (!slices.Equal(pv.Moves, position.Principal.Moves) ||
			pv.Depth != position.Principal.Depth || pv.CandidateCount != position.Principal.CandidateCount) {
			principalDiffs++
		}
	}
	t.Logf("compared %d candidates: score %d, reply %d, pv %d differ; principal line differs in %d/%d positions",
		compared, scoreDiffs, replyDiffs, pvDiffs, principalDiffs, len(corpus.Positions))
	if scoreDiffs+replyDiffs+pvDiffs+principalDiffs > 0 {
		t.Fail()
	}
}
