package gamecore

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

// The corpus is generated by scripts/games_parity_corpus.py from
// backend-python/chess_core.py; CI regenerates it with --check.
type gamesCorpus struct {
	PythonChess string `json:"python_chess"`
	Games       []struct {
		ID       string         `json:"id"`
		Entry    map[string]any `json:"entry"`
		Snapshot map[string]any `json:"snapshot"`
	} `json:"games"`
	Resolve []struct {
		FEN       string  `json:"fen"`
		From      string  `json:"from"`
		To        string  `json:"to"`
		Promotion *string `json:"promotion"`
		UCI       *string `json:"uci"`
	} `json:"resolve"`
	Validity []struct {
		FEN   string `json:"fen"`
		Valid bool   `json:"valid"`
	} `json:"validity"`
}

func loadCorpus(t *testing.T) gamesCorpus {
	t.Helper()
	data, err := os.ReadFile("testdata/python_games_corpus.json")
	if err != nil {
		t.Fatal(err)
	}
	var corpus gamesCorpus
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatal(err)
	}
	return corpus
}

// normalize round-trips through JSON so Go and Python values compare alike.
func normalize(t *testing.T, value any) any {
	t.Helper()
	data, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	var out any
	if err := json.Unmarshal(data, &out); err != nil {
		t.Fatal(err)
	}
	return out
}

func TestSnapshotMatchesPythonCorpus(t *testing.T) {
	corpus := loadCorpus(t)
	if len(corpus.Games) < 100 {
		t.Fatalf("corpus too small: %d games", len(corpus.Games))
	}
	failures := 0
	for _, game := range corpus.Games {
		entry, err := ParseEntry(game.Entry)
		if err != nil {
			t.Fatalf("%s: %v", game.ID, err)
		}
		board, err := LoadBoard(entry)
		if err != nil {
			failures++
			t.Errorf("%s: load: %v (moves=%v)", game.ID, err, entry.Moves)
			continue
		}
		got := normalize(t, board.Snapshot(game.ID, entry)).(map[string]any)
		want := normalize(t, game.Snapshot).(map[string]any)
		if !reflect.DeepEqual(got, want) {
			failures++
			if failures <= 10 {
				for key := range want {
					if !reflect.DeepEqual(got[key], want[key]) {
						t.Errorf("%s: %s go=%v python=%v", game.ID, key, short(got[key]), short(want[key]))
					}
				}
			}
		}
		if !reflect.DeepEqual(board.SANs(), entry.Moves) && !(len(entry.Moves) == 0 && len(board.SANs()) == 0) {
			failures++
			t.Errorf("%s: SAN re-encoding drifted", game.ID)
		}
	}
	if failures > 0 {
		t.Fatalf("%d/%d games differ from Python (python-chess %s)", failures, len(corpus.Games), corpus.PythonChess)
	}
}

func short(value any) any {
	if list, ok := value.([]any); ok && len(list) > 3 {
		return list[len(list)-3:]
	}
	return value
}

func TestResolveMoveMatchesPythonCorpus(t *testing.T) {
	corpus := loadCorpus(t)
	failures := 0
	for _, c := range corpus.Resolve {
		board, err := BoardFromValidFEN(c.FEN)
		if err != nil {
			t.Fatalf("%s: %v", c.FEN, err)
		}
		move, ok := board.ResolveMove(c.From, c.To, c.Promotion)
		got := ""
		if ok {
			got = move.String()
		}
		want := ""
		if c.UCI != nil {
			want = *c.UCI
		}
		if got != want {
			failures++
			if failures <= 10 {
				t.Errorf("%s %s->%s promo=%v: go=%q python=%q", c.FEN, c.From, c.To, deref(c.Promotion), got, want)
			}
		}
	}
	if failures > 0 {
		t.Fatalf("%d/%d resolve cases differ from Python", failures, len(corpus.Resolve))
	}
}

func deref(s *string) any {
	if s == nil {
		return nil
	}
	return *s
}

func TestFENValidityMatchesPythonCorpus(t *testing.T) {
	corpus := loadCorpus(t)
	failures := 0
	for _, c := range corpus.Validity {
		_, err := BoardFromValidFEN(c.FEN)
		if (err == nil) != c.Valid {
			failures++
			t.Errorf("%q: go valid=%v python valid=%v", c.FEN, err == nil, c.Valid)
		}
	}
	if failures > 0 {
		t.Fatalf("%d/%d validity cases differ from Python", failures, len(corpus.Validity))
	}
}
