#!/usr/bin/env python3
"""Build the Pawn Slug 8-row enemy cast v2 from the approved premium raster.

The baseline rows stay byte-for-byte visual sources for pawn/knight/rook. The
five derived classes are generated by the reviewed deterministic 2D passes.
Output is a compact 640x640 WebP/PNG pair suitable for the Godot runtime.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from derive_pawn_slug_enemy_commando_v2 import acquire, decorate_commando, source_from_gdscript
from derive_pawn_slug_enemy_grenadier_v2 import decorate_grenadier
from derive_pawn_slug_enemy_knight_v2 import decorate_knight
from derive_pawn_slug_enemy_queen_v2 import decorate_queen
from derive_pawn_slug_enemy_scout_v2 import decorate_scout
from derive_pawn_slug_enemy_shield_v2 import decorate_shield

CELL = 80
COLS = 8
BASE_ROWS = 3
OUT_ROWS = 8
ALPHA_FLOOR = 4
EXPECTED_SOURCE = (COLS * CELL, BASE_ROWS * CELL)
EXPECTED_WEBP_SHA256 = "df3e038d63722e8ed384b9a3504c109b6f4bc83575c3f9ba7a7ad2900ee84bca"
ROW_SPECS = (
    ("pawn", 0, None),
    ("knight", 1, decorate_knight),
    ("rook", 2, None),
    ("queen", 1, decorate_queen),
    ("grenadier", 0, decorate_grenadier),
    ("scout", 0, decorate_scout),
    ("commando", 0, decorate_commando),
    ("shield", 2, decorate_shield),
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def clean_hidden_rgb(image: Image.Image) -> Image.Image:
    """Drop subvisible alpha haze so linear filtering cannot sample a dark cell background."""
    rgba = image.convert("RGBA")
    px = bytearray(rgba.tobytes())
    for i in range(0, len(px), 4):
        if px[i + 3] <= ALPHA_FLOOR:
            px[i] = px[i + 1] = px[i + 2] = px[i + 3] = 0
    return Image.frombytes("RGBA", rgba.size, bytes(px))


def build(source_path: Path, output_dir: Path) -> dict:
    source = Image.open(source_path).convert("RGBA")
    if source.size != EXPECTED_SOURCE:
        raise ValueError(f"source must be {EXPECTED_SOURCE}, got {source.size}")
    output_dir.mkdir(parents=True, exist_ok=True)
    atlas = Image.new("RGBA", (COLS * CELL, OUT_ROWS * CELL), (0, 0, 0, 0))
    rows = []
    for out_row, (kind, source_row, decorator) in enumerate(ROW_SPECS):
        row = Image.new("RGBA", (COLS * CELL, CELL), (0, 0, 0, 0))
        for frame_index in range(COLS):
            x = frame_index * CELL
            frame = source.crop((x, source_row * CELL, x + CELL, (source_row + 1) * CELL))
            if decorator is not None:
                frame = decorator(frame, frame_index)
            row.alpha_composite(frame, (x, 0))
        row = clean_hidden_rgb(row)
        atlas.alpha_composite(row, (0, out_row * CELL))
        rows.append({"type": kind, "row": out_row, "sourceRow": source_row, "derived": decorator is not None})

    atlas = clean_hidden_rgb(atlas)
    png = output_dir / "enemy-cast-v2.png"
    webp = output_dir / "enemy-cast-v2.webp"
    atlas.save(png, "PNG", optimize=False, compress_level=9)
    atlas.save(webp, "WEBP", lossless=True, method=6, exact=True)

    digest = sha256(webp)
    if digest != EXPECTED_WEBP_SHA256:
        raise ValueError(f"enemy cast v2 WebP drifted: {digest} != {EXPECTED_WEBP_SHA256}")
    report = {
        "schema": 2,
        "scope": "pawn-slug-enemy-cast-v2-runtime",
        "cell": [CELL, CELL,
        ],
        "cols": COLS,
        "rows": OUT_ROWS,
        "size": list(atlas.size),
        "types": rows,
        "webp": {"file": webp.name, "sha256": digest, "bytes": webp.stat().st_size},
        "png": {"file": png.name, "sha256": sha256(png), "bytes": png.stat().st_size},
        "alphaFloor": ALPHA_FLOOR,
        "runtimeReady": True,
    }
    (output_dir / "enemy-cast-v2.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return report


def main() -> None:
    p = argparse.ArgumentParser()
    inputs = p.add_mutually_exclusive_group(required=True)
    inputs.add_argument("--source", type=Path)
    inputs.add_argument("--gdscript", type=Path)
    p.add_argument("--output-dir", type=Path, required=True)
    cfg = p.parse_args()
    if cfg.source is not None:
        report = build(cfg.source, cfg.output_dir)
    else:
        source_spec = source_from_gdscript(cfg.gdscript)
        with tempfile.TemporaryDirectory(prefix="pawnslug-cast-v2-") as tmp:
            source = acquire(source_spec, Path(tmp))
            report = build(source, cfg.output_dir)
    print(f"OK enemy cast v2: {report['size']} · {report['webp']['sha256']}")


if __name__ == "__main__":
    main()
