#!/usr/bin/env python3
"""Pack isolated Pawn Slug enemy frames into the strict Godot 2D atlas.

Input:  frames/<type>/<action>/NN.png (transparent RGBA, 128x128) + frames/grips.json
Output: 8-column atlas (128px cells, one row per type x action), review boards,
        worksheet.json and the runtime grip table (scripts/enemy_grips_v2.gd).

The packer never draws art. It only checks, cleans and places frames: fixed cell,
fixed pivot/foot contract, alpha cleanup of stray specks, deterministic layout.
Frames may come from render_pawn_slug_enemy_frames.py or from Image Generation cuts.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

TYPES = ("pawn", "knight", "rook", "bishop", "queen", "grenadier", "scout", "commando", "shield")
ACTIONS = (
    "idle", "run", "jump", "crouch", "hurt", "climb", "death",
    "shoot", "shoot_up", "shoot_down", "shoot_diag_up", "shoot_diag_down", "shoot_crouch",
)
FRAMES = 8
CELL = 128
FOOT_Y = 116
PIVOT_X = 64
ALPHA_FLOOR = 6


def clean_frame(path: Path) -> Image.Image:
    image = Image.open(path).convert("RGBA")
    if image.size != (CELL, CELL):
        raise SystemExit(f"{path}: frame must be {CELL}x{CELL}, got {image.size}")
    data = np.array(image)
    data[data[..., 3] < ALPHA_FLOOR] = 0
    return Image.fromarray(data, "RGBA")


def build_atlas(frames_root: Path) -> Image.Image:
    atlas = Image.new("RGBA", (FRAMES * CELL, len(TYPES) * len(ACTIONS) * CELL), (0, 0, 0, 0))
    for type_index, enemy_type in enumerate(TYPES):
        for action_index, action in enumerate(ACTIONS):
            for frame in range(FRAMES):
                path = frames_root / enemy_type / action / f"{frame:02d}.png"
                if not path.exists():
                    raise SystemExit(f"missing frame: {path}")
                atlas.alpha_composite(clean_frame(path), (frame * CELL, (type_index * len(ACTIONS) + action_index) * CELL))
    return atlas


def cell(atlas: Image.Image, column: int, row: int) -> Image.Image:
    return atlas.crop((column * CELL, row * CELL, (column + 1) * CELL, (row + 1) * CELL))


def review_boards(atlas: Image.Image, grips: dict, review_dir: Path) -> None:
    review_dir.mkdir(parents=True, exist_ok=True)
    bg = (64, 78, 90, 255)
    cast = Image.new("RGBA", (len(ACTIONS) * CELL, len(TYPES) * CELL), bg)
    for type_index in range(len(TYPES)):
        for action_index in range(len(ACTIONS)):
            cast.alpha_composite(cell(atlas, 3, type_index * len(ACTIONS) + action_index), (action_index * CELL, type_index * CELL))
    cast.save(review_dir / "enemy_cast_v2_review.png", optimize=True)
    for type_index, enemy_type in enumerate(TYPES):
        sheet = Image.new("RGBA", (FRAMES * CELL, len(ACTIONS) * CELL), bg)
        draw = ImageDraw.Draw(sheet)
        for action_index, action in enumerate(ACTIONS):
            for frame in range(FRAMES):
                sheet.alpha_composite(cell(atlas, frame, type_index * len(ACTIONS) + action_index), (frame * CELL, action_index * CELL))
            draw.text((3, action_index * CELL + 2), action, fill=(255, 255, 255, 255))
        sheet.save(review_dir / f"enemy_{enemy_type}_v2_contact_sheet.png", optimize=True)


def body_heights(atlas: Image.Image) -> list[int]:
    """Median idle silhouette height per type; the runtime scales bodies against this."""
    result = []
    for type_index in range(len(TYPES)):
        heights = []
        for frame in range(FRAMES):
            box = cell(atlas, frame, type_index * len(ACTIONS)).getchannel("A").point(lambda v: 255 if v >= 24 else 0).getbbox()
            heights.append(box[3] - box[1])
        result.append(int(sorted(heights)[len(heights) // 2]))
    return result


def grip_gd(grips: dict, heights: list[int]) -> str:
    values: list[str] = []
    for enemy_type in TYPES:
        for action in ACTIONS:
            for row in grips[enemy_type][action]:
                values.extend([f"{row['x']:.2f}", f"{row['y']:.2f}", f"{row['a']:.4f}", str(int(row["v"]))])
    lines = [
        "# Generated by scripts/art/pack_pawn_slug_enemy_v2.py. Do not edit by hand.",
        "# Layout: [type][action][frame] -> x, y (weapon grip anchor in atlas cell px), angle (rad), visible.",
        "class_name EnemyGripsV2",
        "",
        f"const TYPES := {json.dumps(list(TYPES))}",
        f"const ACTIONS := {json.dumps(list(ACTIONS))}",
        f"const FRAMES := {FRAMES}",
        "const STRIDE := 4",
        "# Median idle silhouette height in atlas px, per type index.",
        f"const BODY_HEIGHT := {json.dumps(heights)}",
        "static var DATA := PackedFloat32Array([",
    ]
    for start in range(0, len(values), 16):
        lines.append("    " + ", ".join(values[start:start + 16]) + ",")
    lines += [
        "])",
        "",
        "static func lookup(type_index: int, action_index: int, frame: int) -> Dictionary:",
        "    var base := ((type_index * ACTIONS.size() + action_index) * FRAMES + frame) * STRIDE",
        "    return {\"x\": DATA[base], \"y\": DATA[base + 1], \"angle\": DATA[base + 2], \"visible\": DATA[base + 3] > 0.5}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--frames-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--review", type=Path, required=True, help="review directory")
    parser.add_argument("--worksheet", type=Path, required=True)
    parser.add_argument("--grips-gd", type=Path, required=True)
    parser.add_argument("--source", default="procedural-2d-rig-v2 (render_pawn_slug_enemy_frames.py)")
    args = parser.parse_args()

    grips_doc = json.loads((args.frames_root / "grips.json").read_text(encoding="utf-8"))
    grips = grips_doc["grips"]
    atlas = build_atlas(args.frames_root)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    atlas.save(args.output, "PNG", optimize=True)
    review_boards(atlas, grips, args.review)
    args.grips_gd.write_text(grip_gd(grips, body_heights(atlas)), encoding="utf-8")

    digest = hashlib.sha256(args.output.read_bytes()).hexdigest()
    worksheet = {
        "worksheet": "pawn-slug-enemies-v2",
        "status": "generated-local-awaiting-validation",
        "atlas": {
            "path": str(args.output.as_posix()), "width": atlas.width, "height": atlas.height,
            "cell": CELL, "columns": FRAMES, "rows": len(TYPES) * len(ACTIONS), "sha256": digest,
        },
        "types": list(TYPES),
        "actions": list(ACTIONS),
        "frames_per_action": FRAMES,
        "pivot_x": PIVOT_X,
        "foot_y": FOOT_Y,
        "weapons": ["pistol", "machinegun", "shotgun", "panzerfaust"],
        "weapon_mode": "runtime overlay anchored per frame by enemy_grips_v2.gd (grip x/y/angle/visible)",
        "source": args.source,
        "resume": "regenerate: render_pawn_slug_enemy_frames.py -> pack_pawn_slug_enemy_v2.py -> validate_pawn_slug_enemy_v2.py",
    }
    args.worksheet.parent.mkdir(parents=True, exist_ok=True)
    args.worksheet.write_text(json.dumps(worksheet, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(worksheet["atlas"], indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
