// Package gameops ports backend-python/operation_idempotency_core.py and the
// request models it fingerprints (api_models.NewGameRequest, MoveRequest).
// A retried create/move/undo may reach Python or Go while both serve games,
// so fingerprints and deterministic ids must be byte-identical; a corpus
// generated by scripts/games_ops_corpus.py pins them.
package gameops

import (
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
	"unicode/utf16"
)

// PyInt marks a Python int: json.dumps writes ints and floats differently
// (50 vs 50.0), and fingerprints hash those exact bytes.
type PyInt int64

// pyJSON is json.dumps(value, sort_keys=True, separators=(",", ":"),
// ensure_ascii=True) for the value shapes the fingerprints use.
func pyJSON(value any) (string, error) {
	var b strings.Builder
	if err := writePyJSON(&b, value); err != nil {
		return "", err
	}
	return b.String(), nil
}

func writePyJSON(b *strings.Builder, value any) error {
	switch v := value.(type) {
	case nil:
		b.WriteString("null")
	case bool:
		if v {
			b.WriteString("true")
		} else {
			b.WriteString("false")
		}
	case PyInt:
		b.WriteString(strconv.FormatInt(int64(v), 10))
	case float64:
		b.WriteString(pyFloatRepr(v))
	case string:
		writePyString(b, v)
	case map[string]any:
		keys := make([]string, 0, len(v))
		for k := range v {
			keys = append(keys, k)
		}
		sort.Strings(keys) // UTF-8 byte order is code point order
		b.WriteByte('{')
		for i, k := range keys {
			if i > 0 {
				b.WriteByte(',')
			}
			writePyString(b, k)
			b.WriteByte(':')
			if err := writePyJSON(b, v[k]); err != nil {
				return err
			}
		}
		b.WriteByte('}')
	case []any:
		b.WriteByte('[')
		for i, item := range v {
			if i > 0 {
				b.WriteByte(',')
			}
			if err := writePyJSON(b, item); err != nil {
				return err
			}
		}
		b.WriteByte(']')
	default:
		return fmt.Errorf("pyjson: unsupported %T", value)
	}
	return nil
}

// pyFloatRepr is Python's repr(float) (json.dumps uses float.__repr__).
func pyFloatRepr(f float64) string {
	switch {
	case math.IsNaN(f):
		return "NaN"
	case math.IsInf(f, 1):
		return "Infinity"
	case math.IsInf(f, -1):
		return "-Infinity"
	case f == 0:
		if math.Signbit(f) {
			return "-0.0"
		}
		return "0.0"
	}
	sign := ""
	if f < 0 {
		sign, f = "-", -f
	}
	// Shortest round-trip digits, as Python's repr.
	sci := strconv.FormatFloat(f, 'e', -1, 64) // d.ddde±XX
	mantissa, expPart, _ := strings.Cut(sci, "e")
	digits := strings.Replace(mantissa, ".", "", 1)
	exp, _ := strconv.Atoi(expPart)
	decpt := exp + 1
	if decpt > -4 && decpt <= 16 {
		switch {
		case decpt <= 0:
			return sign + "0." + strings.Repeat("0", -decpt) + digits
		case decpt >= len(digits):
			return sign + digits + strings.Repeat("0", decpt-len(digits)) + ".0"
		default:
			return sign + digits[:decpt] + "." + digits[decpt:]
		}
	}
	out := digits[:1]
	if len(digits) > 1 {
		out += "." + digits[1:]
	}
	e := decpt - 1
	expSign := "+"
	if e < 0 {
		expSign, e = "-", -e
	}
	return fmt.Sprintf("%s%se%s%02d", sign, out, expSign, e)
}

func writePyString(b *strings.Builder, s string) {
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		case '\b':
			b.WriteString(`\b`)
		case '\f':
			b.WriteString(`\f`)
		default:
			if r >= 0x20 && r <= 0x7e {
				b.WriteRune(r)
			} else if r > 0xffff {
				hi, lo := utf16.EncodeRune(r)
				fmt.Fprintf(b, `\u%04x\u%04x`, hi, lo)
			} else {
				fmt.Fprintf(b, `\u%04x`, r)
			}
		}
	}
	b.WriteByte('"')
}
