// Static achievement metadata lives separately from progress evaluation/storage so
// read-only consumers do not pull tournament, rating, Combat and puzzle modules.
export const ACHIEVEMENTS = [
  { id: 'first_game', name: 'Primer movimiento', description: 'Jugaste tu primera partida contra la CPU.' },
  { id: 'ten_games', name: 'Diez partidas', description: 'Jugaste 10 partidas contra la CPU.' },
  { id: 'fifty_games', name: 'Cincuenta partidas', description: 'Jugaste 50 partidas contra la CPU.' },
  { id: 'tournament_wins_5', name: 'Racha de cinco', description: 'Ganaste 5 partidas de torneo.' },
  { id: 'tournament_level_5', name: 'Nivel 5', description: 'Llegaste a nivel 5 en el torneo.' },
  { id: 'tournament_level_10', name: 'Nivel 10', description: 'Llegaste a nivel 10 en el torneo.' },
  { id: 'rating_intermediate', name: 'Intermedio', description: 'Tu rating llegó a "Intermedio" (1300+).' },
  { id: 'rating_advanced', name: 'Avanzado', description: 'Tu rating llegó a "Avanzado" (1600+).' },
  { id: 'rating_master', name: 'Maestro', description: 'Tu rating llegó a "Maestro" (1900+).' },
  { id: 'combat_gold_piece', name: 'Pieza dorada', description: 'Una pieza de tu ejército llegó a nivel 6 o más.' },
  { id: 'combat_reviver', name: 'Resucitador', description: 'Reviviste una pieza caída con créditos de campaña.' },
  { id: 'combat_flawless', name: 'Victoria perfecta', description: 'Ganaste una batalla de combate sin perder ninguna pieza.' },
  { id: 'puzzles_10', name: 'Resolvedor', description: 'Resolviste 10 puzzles.' },
  { id: 'puzzles_50', name: 'Especialista en puzzles', description: 'Resolviste 50 puzzles.' },
  { id: 'daily_streak_3', name: 'Tres días sin excusas', description: 'Mantuviste una racha diaria de 3 días.' },
  { id: 'daily_streak_7', name: 'Semana de guardia', description: 'Mantuviste una racha diaria de 7 días.' },
  { id: 'daily_streak_30', name: 'Funcionario del tablero', description: 'Alcanzaste una racha diaria de 30 días.' },
  { id: 'daily_challenges_10', name: 'Diez casos cerrados', description: 'Completaste 10 desafíos diarios.' },
  { id: 'daily_full_first', name: 'Triple corona', description: 'Completaste los tres desafíos de un mismo día.' },
  { id: 'daily_full_7', name: 'Siete plenos', description: 'Firmaste 7 plenos diarios.' },
  { id: 'daily_clean_full_3', name: 'Expediente impecable', description: 'Completaste 3 plenos sin un solo fallo.' },
  { id: 'rivalry_25', name: 'Veinticinco asaltos', description: 'Completaste 25 partidas competitivas contra la misma CPU.' },
  { id: 'rivalry_streak_3', name: 'Tres al hilo', description: 'Encadenaste 3 victorias competitivas contra la CPU.' },
  { id: 'rivalry_hard_75', name: 'Tumbagigantes', description: 'Derrotaste a la CPU en dificultad 75 o superior.' },
  { id: 'crime_missed_mate', name: 'Mate, ¿qué mate?', description: 'Ignoraste un mate en una.', kind: 'shame' },
  { id: 'crime_allowed_mate', name: 'Entrega urgente', description: 'Dejaste mate en una a la CPU.', kind: 'shame' },
  { id: 'crime_queen_to_pawn', name: 'Revolución proletaria inversa', description: 'Un peón enemigo capturó tu dama.', kind: 'shame' },
  { id: 'crime_queen_exposed', name: 'Parking premium', description: 'Dejaste tu dama directamente al alcance de un peón.', kind: 'shame' },
  { id: 'crime_stalemate', name: 'Diplomacia involuntaria', description: 'Convertiste una ventaja ganadora en tablas por ahogado.', kind: 'shame' },
  { id: 'crime_knight_fork', name: 'Geometría hostil', description: 'La CPU te clavó una horquilla de caballo seria.', kind: 'shame' },
  { id: 'feat_pawn_queen', name: 'David contra Goliat', description: 'Tu peón capturó la dama rival.', kind: 'glory' },
  { id: 'feat_mate', name: 'Cierre por derribo', description: 'Diste jaque mate a la CPU.', kind: 'glory' },
  { id: 'feat_promotion', name: 'Ascenso meteórico', description: 'Coronaste un peón.', kind: 'glory' },
  { id: 'feat_skewer', name: 'Brocheta real', description: 'Ejecutaste un ensartado sobre el rey.', kind: 'glory' },
];
