import { isActiveSessionRoute } from './activeSessionRoutes.js';
import { strictInvariant, transition } from './stateTransition.js';

export const ACTIVE_SESSION_STATE = Object.freeze({
  IDLE: 'idle',
  CREATING: 'creating',
  RESTORING: 'restoring',
  ACTIVE: 'active',
  RECONNECTING: 'reconnecting',
  RETRYABLE_ERROR: 'retryable_error',
  IRRECOVERABLE: 'irrecoverable',
  DISCARDED: 'discarded',
  FINISHED: 'finished',
});

export const ACTIVE_SESSION_EVENT = Object.freeze({
  CREATE: 'create',
  CREATED: 'created',
  CREATE_FAILURE: 'create_failure',
  CANCEL_CREATE: 'cancel_create',
  RESTORE: 'restore',
  RESTORED: 'restored',
  RECONNECT: 'reconnect',
  RECONNECTED: 'reconnected',
  TRANSIENT_FAILURE: 'transient_failure',
  IRRECOVERABLE_FAILURE: 'irrecoverable_failure',
  STALE: 'stale',
  DISCARD: 'discard',
  FINISH: 'finish',
});

const T = Object.freeze({
  [ACTIVE_SESSION_STATE.IDLE]: {
    [ACTIVE_SESSION_EVENT.CREATE]: ACTIVE_SESSION_STATE.CREATING,
    [ACTIVE_SESSION_EVENT.RESTORE]: ACTIVE_SESSION_STATE.RESTORING,
    [ACTIVE_SESSION_EVENT.DISCARD]: ACTIVE_SESSION_STATE.DISCARDED,
  },
  [ACTIVE_SESSION_STATE.CREATING]: {
    [ACTIVE_SESSION_EVENT.CREATED]: ACTIVE_SESSION_STATE.ACTIVE,
    [ACTIVE_SESSION_EVENT.CREATE_FAILURE]: ACTIVE_SESSION_STATE.IDLE,
    [ACTIVE_SESSION_EVENT.CANCEL_CREATE]: ACTIVE_SESSION_STATE.IDLE,
    [ACTIVE_SESSION_EVENT.DISCARD]: ACTIVE_SESSION_STATE.DISCARDED,
  },
  [ACTIVE_SESSION_STATE.RESTORING]: {
    [ACTIVE_SESSION_EVENT.RESTORED]: ACTIVE_SESSION_STATE.ACTIVE,
    [ACTIVE_SESSION_EVENT.TRANSIENT_FAILURE]: ACTIVE_SESSION_STATE.RETRYABLE_ERROR,
    [ACTIVE_SESSION_EVENT.IRRECOVERABLE_FAILURE]: ACTIVE_SESSION_STATE.IRRECOVERABLE,
    [ACTIVE_SESSION_EVENT.STALE]: ACTIVE_SESSION_STATE.IDLE,
    [ACTIVE_SESSION_EVENT.DISCARD]: ACTIVE_SESSION_STATE.DISCARDED,
  },
  [ACTIVE_SESSION_STATE.ACTIVE]: {
    [ACTIVE_SESSION_EVENT.CREATE]: ACTIVE_SESSION_STATE.CREATING,
    [ACTIVE_SESSION_EVENT.CANCEL_CREATE]: ACTIVE_SESSION_STATE.IDLE,
    [ACTIVE_SESSION_EVENT.RESTORE]: ACTIVE_SESSION_STATE.RESTORING,
    [ACTIVE_SESSION_EVENT.RECONNECT]: ACTIVE_SESSION_STATE.RECONNECTING,
    [ACTIVE_SESSION_EVENT.TRANSIENT_FAILURE]: ACTIVE_SESSION_STATE.RETRYABLE_ERROR,
    [ACTIVE_SESSION_EVENT.FINISH]: ACTIVE_SESSION_STATE.FINISHED,
    [ACTIVE_SESSION_EVENT.DISCARD]: ACTIVE_SESSION_STATE.DISCARDED,
  },
  [ACTIVE_SESSION_STATE.RECONNECTING]: {
    [ACTIVE_SESSION_EVENT.RECONNECTED]: ACTIVE_SESSION_STATE.ACTIVE,
    [ACTIVE_SESSION_EVENT.TRANSIENT_FAILURE]: ACTIVE_SESSION_STATE.RETRYABLE_ERROR,
    [ACTIVE_SESSION_EVENT.STALE]: ACTIVE_SESSION_STATE.IDLE,
    [ACTIVE_SESSION_EVENT.DISCARD]: ACTIVE_SESSION_STATE.DISCARDED,
  },
  [ACTIVE_SESSION_STATE.RETRYABLE_ERROR]: {
    [ACTIVE_SESSION_EVENT.RESTORE]: ACTIVE_SESSION_STATE.RESTORING,
    [ACTIVE_SESSION_EVENT.RECONNECT]: ACTIVE_SESSION_STATE.RECONNECTING,
    [ACTIVE_SESSION_EVENT.STALE]: ACTIVE_SESSION_STATE.IDLE,
    [ACTIVE_SESSION_EVENT.IRRECOVERABLE_FAILURE]: ACTIVE_SESSION_STATE.IRRECOVERABLE,
    [ACTIVE_SESSION_EVENT.DISCARD]: ACTIVE_SESSION_STATE.DISCARDED,
  },
  [ACTIVE_SESSION_STATE.IRRECOVERABLE]: {
    [ACTIVE_SESSION_EVENT.DISCARD]: ACTIVE_SESSION_STATE.DISCARDED,
    [ACTIVE_SESSION_EVENT.STALE]: ACTIVE_SESSION_STATE.IDLE,
  },
  [ACTIVE_SESSION_STATE.DISCARDED]: {
    [ACTIVE_SESSION_EVENT.CREATE]: ACTIVE_SESSION_STATE.CREATING,
    [ACTIVE_SESSION_EVENT.RESTORE]: ACTIVE_SESSION_STATE.RESTORING,
  },
  [ACTIVE_SESSION_STATE.FINISHED]: {
    [ACTIVE_SESSION_EVENT.CREATE]: ACTIVE_SESSION_STATE.CREATING,
    [ACTIVE_SESSION_EVENT.DISCARD]: ACTIVE_SESSION_STATE.DISCARDED,
  },
});

export function activeSessionTransition(state, event) {
  return transition(T, state, event);
}

export function assertActiveSessionInvariant({ state, savedSession = null, route = null, gameId = null } = {}) {
  strictInvariant(Object.values(ACTIVE_SESSION_STATE).includes(state), `unknown active-session state ${state}`);
  if ([ACTIVE_SESSION_STATE.RESTORING, ACTIVE_SESSION_STATE.ACTIVE, ACTIVE_SESSION_STATE.RECONNECTING, ACTIVE_SESSION_STATE.RETRYABLE_ERROR].includes(state)) {
    strictInvariant(Boolean(gameId || savedSession?.gameId), `${state} requires a game id`);
  }
  if (savedSession?.route) {
    strictInvariant(isActiveSessionRoute(savedSession.route), `unsupported route ${savedSession.route}`);
  }
  if (route && isActiveSessionRoute(route) && state === ACTIVE_SESSION_STATE.DISCARDED) {
    strictInvariant(false, 'discarded session cannot remain on an active game route');
  }
  return true;
}
