// ambientProfiles.js — identidades de mezcla/arreglo por tema estructurado.
// Datos puros: sin AudioContext, timers ni estado de reproducción.

const STRUCTURED_FEELS = Object.freeze({
  // Identidad por AUSENCIA además de timbre. Cada familia decide
  // qué capas existen; no todo tema necesita lead+counter+chords+bass+drums.
  // El objetivo es que la silueta se reconozca antes que el preset.
  alexandriaLounge: Object.freeze({
    family: 'alexandria-minimal-piano-trio', preserveSectionOrder: true,
    harmonyPath: [0, 0, -2, 0, 3, 0],
    swing: 0.16, warmth: 0.98, releaseScale: 1.22, space: 0.13, delayMs: 165,
    leadInstrument: 'felt', chordInstrument: 'felt', bassInstrument: 'uprightBass',
    chordHoldSteps: 16, bassHoldSteps: 4.2,
    layers: { lead: false, counter: false, chords: true, bass: true, drums: true, signature: true },
    mix: { lead: 0, counter: 0, bass: 0.9, chord: 0.58 },
    percussion: { period: 16, kit: 'brush-jazz', punch: 0.82, pattern: { 0: 'B', 8: 'H' } },
    signature: { instrument: 'felt', sections: [0, 1, 2, 3], everyCycles: 1, repeatPeriod: 32,
      durationSteps: 6.5, volume: 0.56, motif: { 2: 74, 10: 69, 18: 72, 27: 67 } },
  }),
  cairoAfterHours: Object.freeze({
    family: 'cairo-rhodes-horn-noir', preserveSectionOrder: true,
    harmonyPath: [0, -2, 0, 0, -5, 0],
    swing: 0.035, warmth: 0.74, releaseScale: 1.48, space: 0.24, delayMs: 285,
    leadInstrument: 'mutedHorn', chordInstrument: 'rhodesWarm', bassInstrument: 'uprightBass',
    chordHoldSteps: 22, bassHoldSteps: 7,
    layers: { lead: false, counter: false, chords: true, bass: true, drums: true, signature: true },
    mix: { lead: 0, counter: 0, bass: 1.08, chord: 0.86 },
    percussion: { period: 32, kit: 'brush-jazz', punch: 0.72, pattern: { 0: 'B', 24: 'H' } },
    signature: { instrument: 'mutedHorn', sections: [0, 1, 2, 3], everyCycles: 1, repeatPeriod: 40,
      durationSteps: 10, volume: 0.62, motif: { 5: 69, 17: 65.5, 29: 62, 37: 60.5 } },
  }),
  cairoQuietNoir: Object.freeze({
    family: 'cairo-muted-oud-noir', preserveSectionOrder: true,
    harmonyPath: [0, -2, 0, 3, 0, -5],
    swing: 0.14, warmth: 0.86, releaseScale: 1.28, space: 0.16, delayMs: 190,
    leadInstrument: 'mutedHorn', counterInstrument: 'oudJazz', chordInstrument: 'rhodesWarm', bassInstrument: 'uprightBass',
    chordHoldSteps: 18, bassHoldSteps: 5.2,
    layers: { lead: true, counter: true, chords: true, bass: true, drums: true, signature: true },
    mix: { lead: 0.62, counter: 0.42, bass: 0.92, chord: 0.54 },
    percussion: { period: 24, kit: 'cairo-hand', punch: 0.66, pattern: { 0: 'K', 7: 'H', 12: 'B', 19: 'H' } },
    signature: { instrument: 'oudJazz', sections: [0, 2], everyCycles: 2, repeatPeriod: 72,
      durationSteps: 4.8, volume: 0.28, motif: { 9: 62, 27: 65, 45: 60, 63: 58 } },
  }),
  nileBalconyAir: Object.freeze({
    family: 'nile-ney-vibes-river-nocturne', preserveSectionOrder: true,
    harmonyPath: [0, 0, 5, 0, -2, 0],
    swing: 0, warmth: 1.06, releaseScale: 1.82, space: 0.39, delayMs: 430,
    leadInstrument: 'ney', counterInstrument: 'vibes', chordInstrument: 'epiano', bassInstrument: 'cello',
    chordHoldSteps: 28, bassHoldSteps: 18, drumMode: 'none',
    layers: { lead: true, counter: true, chords: true, bass: true, drums: false, signature: true },
    mix: { lead: 0.46, counter: 0.30, bass: 0.38, chord: 0.34 },
    percussion: { period: 48, kit: 'none', punch: 0, pattern: {} },
    signature: { instrument: 'ney', sections: [1, 3], everyCycles: 2, repeatPeriod: 96,
      durationSteps: 12, volume: 0.18, motif: { 18: 76, 50: 72, 82: 69 } },
  }),
  beirutSixEight: Object.freeze({
    family: 'beirut-buzuq-darbuka-6-8', preserveSectionOrder: true,
    harmonyPath: [0, 0, 0, -2, 0, 5],
    swing: 0, warmth: 0.86, releaseScale: 0.96, space: 0.07, delayMs: 105,
    bassInstrument: 'uprightBass', bassHoldSteps: 3.2,
    layers: { lead: false, counter: false, chords: false, bass: true, drums: true, signature: true },
    mix: { lead: 0, counter: 0, bass: 0.72, chord: 0 },
    percussion: { period: 12, kit: 'darbuka', punch: 1.42, pattern: { 0: 'K', 3: 'H', 5: 'W', 6: 'S', 9: 'H', 11: 'W' } },
    signature: { instrument: 'buzuq', sections: [0, 1, 2, 3], everyCycles: 1, repeatPeriod: 24,
      durationSteps: 2.4, volume: 0.9, motif: { 0: 64, 3: 68, 6: 71, 10: 69, 15: 65, 21: 62.5 } },
  }),
  damascusDrone: Object.freeze({
    family: 'damascus-cello-ney-drone', preserveSectionOrder: true,
    harmonyPath: [0, 0, -2, -2, 0, 0],
    swing: 0, warmth: 0.6, releaseScale: 1.78, space: 0.34, delayMs: 380,
    chordInstrument: 'pad', bassInstrument: 'cello', chordHoldSteps: 40, bassHoldSteps: 16,
    drumMode: 'none',
    layers: { lead: false, counter: false, chords: true, bass: true, drums: false, signature: true },
    mix: { lead: 0, counter: 0, bass: 0.56, chord: 0.52 },
    percussion: { period: 64, kit: 'none', punch: 0, pattern: {} },
    signature: { instrument: 'ney', sections: [0, 1, 2, 3], everyCycles: 1, repeatPeriod: 64,
      durationSteps: 15, volume: 0.54, motif: { 9: 74, 31: 69, 53: 66 } },
  }),
  istanbulBroken: Object.freeze({
    family: 'istanbul-clarinet-frame-9-8', preserveSectionOrder: true,
    harmonyPath: [0, 0, 2, 0, -2, 0],
    swing: 0, warmth: 0.86, releaseScale: 1.03, space: 0.09, delayMs: 108,
    bassInstrument: 'uprightBass', bassHoldSteps: 5.6,
    // Estambul deja de ser un motivo corto sobre clicks. Recuperamos las frases
    // completas de clarinete/qanun escritas en cada sección y mantenemos la
    // firma sólo como respuesta ocasional. Más melodía, menos metrónomo con fez.
    layers: { lead: true, counter: true, chords: false, bass: true, drums: true, signature: true },
    mix: { lead: 0.76, counter: 0.58, bass: 0.90, chord: 0 },
    // 18 pasos = 9/8. Dos dums/kicks sostienen el ciclo; brush y tak quedan
    // atrás. Eliminamos los woodblocks que daban buena parte del "chiu-chiu".
    percussion: { period: 18, kit: 'istanbul-frame', punch: 1.34, pattern: { 0: 'K', 4: 'B', 8: 'K', 12: 'H', 16: 'B' } },
    signature: { instrument: 'clarinet', sections: [0, 1, 2, 3], everyCycles: 2, repeatPeriod: 54,
      durationSteps: 4.4, volume: 0.42, motif: { 2: 67, 10: 71, 18: 68, 28: 65, 38: 63, 47: 67 } },
  }),
  tangierWalking: Object.freeze({
    family: 'tangier-dry-walking-club', preserveSectionOrder: true,
    harmonyPath: [0, -2, 0, 5, 0, -2],
    swing: 0.11, warmth: 0.76, releaseScale: 0.9, space: 0.045, delayMs: 78,
    bassInstrument: 'uprightBass', bassHoldSteps: 2.4,
    layers: { lead: false, counter: false, chords: false, bass: true, drums: true, signature: true },
    mix: { lead: 0, counter: 0, bass: 1.26, chord: 0 },
    percussion: { period: 12, kit: 'maghreb-hand', punch: 1.22, pattern: { 0: 'K', 5: 'W', 6: 'S', 11: 'W' } },
    signature: { instrument: 'mutedHorn', sections: [0, 1, 2, 3], everyCycles: 1, repeatPeriod: 24,
      durationSteps: 4.8, volume: 0.58, motif: { 3: 65, 11: 63, 19: 70 } },
  }),
  granadaChamber: Object.freeze({
    family: 'granada-guitar-chamber', preserveSectionOrder: true,
    harmonyPath: [0, 0, 5, 3, 0, 0],
    swing: 0, warmth: 1.0, releaseScale: 1.1, space: 0.2, delayMs: 210,
    chordInstrument: 'felt', bassInstrument: 'pizz', chordHoldSteps: 18, bassHoldSteps: 3.0,
    drumMode: 'none',
    layers: { lead: false, counter: false, chords: true, bass: true, drums: false, signature: true },
    mix: { lead: 0, counter: 0, bass: 0.5, chord: 0.48 },
    percussion: { period: 32, kit: 'none', punch: 0, pattern: {} },
    signature: { instrument: 'guitar2', sections: [0, 1, 2, 3], everyCycles: 1, repeatPeriod: 48,
      durationSteps: 3.1, volume: 0.72, motif: { 0: 64, 7: 65, 15: 68, 23: 63, 30: 64, 39: 61, 46: 64 } },
  }),

  // Familias secundarias conservan el refactor anterior hasta que las siete
  // siluetas principales estén validadas al oído.
  beirutRooftop: Object.freeze({
    family: 'beirut-rooftop', preserveSectionOrder: true,
    harmonyPath: [0, 0, -2, 0, 0, 5, 0, -2, 0],
    swing: 0.17, warmth: 0.84, releaseScale: 1.12,
    chordInstrument: 'rhodesWarm', bassInstrument: 'uprightBass',
    chordHoldSteps: 11, bassHoldSteps: 3.8,
    percussion: { period: 16, kit: 'rooftop-jazz', punch: 1.14, pattern: { 0: 'B', 4: 'H', 8: 'S', 12: 'H' } },
  }),
  levantBlue: Object.freeze({
    family: 'levant-blue', preserveSectionOrder: true,
    harmonyPath: [0, 0, 0, -2, -2, 0, 0, 3, 0],
    swing: 0.06, warmth: 0.72, releaseScale: 1.34,
    bassInstrument: 'uprightBass', chordHoldSteps: 16, bassHoldSteps: 5.5,
    percussion: { period: 16, kit: 'frame-drum', punch: 1.1, pattern: { 0: 'K', 8: 'B', 12: 'H' } },
  }),
  maghrebVelvet: Object.freeze({
    family: 'maghreb-velvet', preserveSectionOrder: true,
    harmonyPath: [0, 0, 0, -2, 0, 0, 5, 0],
    swing: 0.12, warmth: 0.74, releaseScale: 1.26,
    chordInstrument: 'rhodesWarm', bassInstrument: 'uprightBass',
    chordHoldSteps: 14, bassHoldSteps: 4.4,
    percussion: { period: 16, kit: 'maghreb-hand', punch: 1.12, pattern: { 0: 'K', 4: 'H', 8: 'B', 12: 'H' } },
  }),
  andalusWarm: Object.freeze({
    family: 'andalus-warm', preserveSectionOrder: true,
    harmonyPath: [0, 0, 5, 5, 0, 0, -2, 0],
    swing: 0.09, warmth: 0.9, releaseScale: 1.08,
    bassInstrument: 'uprightBass', chordHoldSteps: 10, bassHoldSteps: 3.5,
    percussion: { period: 16, kit: 'andalus-hand', punch: 1.16, pattern: { 0: 'K', 4: 'H', 8: 'S', 12: 'H' } },
  }),

  zugzwangWaltz: Object.freeze({
    family: 'viennese-waltz-chamber', preserveSectionOrder: true,
    harmonyPath: [0, 0, 5, 0, -2, 0], swing: 0, warmth: 0.96, releaseScale: 1.2, space: 0.16, delayMs: 185,
    chordInstrument: 'felt', bassInstrument: 'cello', chordHoldSteps: 8, bassHoldSteps: 7,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: false },
    mix: { lead: 0.72, counter: 0, bass: 0.58, chord: 0.52 },
    percussion: { period: 24, kit: 'legacy', punch: 0.42, pattern: {0:'W',8:'W',16:'W'} },
  }),
  bishopBlues: Object.freeze({
    family: 'late-night-blues-12-8', preserveSectionOrder: true,
    harmonyPath: [0, 0, 5, 0, 7, 5], swing: 0.24, warmth: 0.82, releaseScale: 1.18, space: 0.11, delayMs: 145,
    chordInstrument: 'rhodesWarm', bassInstrument: 'uprightBass', chordHoldSteps: 12, bassHoldSteps: 3,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: false },
    mix: { lead: 0.67, counter: 0, bass: 1.05, chord: 0.55 },
    percussion: { period: 12, kit: 'brush-jazz', punch: 0.92, pattern: {0:'B',6:'H'} },
  }),
  winterLibrary: Object.freeze({
    family: 'snow-library-minimal', preserveSectionOrder: true,
    harmonyPath: [0, 0, -2, 0], swing: 0, warmth: 0.72, releaseScale: 1.72, space: 0.3, delayMs: 360,
    chordInstrument: 'felt', bassInstrument: 'cello', chordHoldSteps: 18, bassHoldSteps: 16, drumMode: 'none',
    layers: { lead: true, counter: false, chords: true, bass: true, drums: false, signature: true },
    mix: { lead: 0.42, counter: 0, bass: 0.42, chord: 0.38 },
    percussion: { period: 32, kit: 'none', punch: 0, pattern: {} },
    signature: { instrument: 'felt', sections: [0,1], everyCycles: 2, repeatPeriod: 64, durationSteps: 8.5, volume: 0.2, motif: {15:76,47:72} },
  }),
  analogBunker: Object.freeze({
    family: 'cold-analog-sequencer', preserveSectionOrder: true,
    harmonyPath: [0, 0, 1, 0, -1, 0], swing: 0, warmth: 0.58, releaseScale: 0.72, space: 0.025, delayMs: 70,
    bassInstrument: 'synthbass', bassHoldSteps: 2,
    layers: { lead: true, counter: false, chords: false, bass: true, drums: true, signature: false },
    mix: { lead: 0.72, counter: 0, bass: 1.2, chord: 0 },
    percussion: { period: 20, kit: 'legacy', punch: 1.2, pattern: {0:'K',5:'H',10:'S',15:'H'} },
  }),
  queenRequiem: Object.freeze({
    family: 'organ-choir-requiem', preserveSectionOrder: true,
    harmonyPath: [0, 0, -2, -5, 0], swing: 0, warmth: 0.66, releaseScale: 1.85, space: 0.32, delayMs: 410,
    chordInstrument: 'organ', bassInstrument: 'organbass', chordHoldSteps: 24, bassHoldSteps: 18, drumMode: 'none',
    layers: { lead: true, counter: false, chords: true, bass: true, drums: false, signature: false },
    mix: { lead: 0.42, counter: 0, bass: 0.52, chord: 0.56 },
    percussion: { period: 32, kit: 'none', punch: 0, pattern: {} },
  }),
  nightFreight: Object.freeze({
    family: 'motorik-night-freight', preserveSectionOrder: true,
    harmonyPath: [0, 0, -1, 0, 2, 0], swing: 0, warmth: 0.68, releaseScale: 0.82, space: 0.06, delayMs: 105,
    bassInstrument: 'synthbass', chordInstrument: 'pad', chordHoldSteps: 24, bassHoldSteps: 3,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: false },
    mix: { lead: 0.44, counter: 0, bass: 1.08, chord: 0.32 },
    percussion: { period: 24, kit: 'legacy', punch: 1.05, pattern: {0:'K',6:'H',12:'W',18:'H'} },
  }),
  mistSpa: Object.freeze({
    family: 'cedar-spa-breath', preserveSectionOrder: true, harmonyPath: [0,0,5,0,-2,0], swing: 0, warmth: 1.1, releaseScale: 1.75, space: 0.42, delayMs: 430,
    chordInstrument: 'singingBowl', bassInstrument: 'pad', chordHoldSteps: 28, bassHoldSteps: 24, drumMode: 'none',
    layers: { lead: true, counter: false, chords: true, bass: true, drums: false, signature: false }, mix: { lead: 0.42, counter: 0, bass: 0.30, chord: 0.38 },
    percussion: { period: 32, kit: 'none', punch: 0, pattern: {} },
  }),
  moonOnsen: Object.freeze({
    family: 'onsen-wood-glass', preserveSectionOrder: true, harmonyPath: [0,0,3,0,-2,0], swing: 0, warmth: 1.04, releaseScale: 1.5, space: 0.36, delayMs: 360,
    chordInstrument: 'glass', bassInstrument: 'cello', chordHoldSteps: 20, bassHoldSteps: 18,
    layers: { lead: true, counter: true, chords: true, bass: true, drums: true, signature: false }, mix: { lead: 0.40, counter: 0.28, bass: 0.32, chord: 0.30 },
    percussion: { period: 40, kit: 'brush-jazz', punch: 0.28, pattern: {8:'B',28:'B'} },
  }),
  postRockMidnight: Object.freeze({
    family: 'post-rock-crescendo', preserveSectionOrder: true, harmonyPath: [0,0,-2,5,0,3], swing: 0, warmth: 0.76, releaseScale: 1.28, space: 0.16, delayMs: 190,
    chordInstrument: 'pad', bassInstrument: 'bass', chordHoldSteps: 24, bassHoldSteps: 5,
    layers: { lead: true, counter: true, chords: true, bass: true, drums: true, signature: false }, mix: { lead: 0.68, counter: 0.42, bass: 0.88, chord: 0.38 },
    percussion: { period: 16, kit: 'legacy', punch: 0.96, pattern: {0:'K',4:'H',8:'S',12:'H'} },
  }),
  rookGarage: Object.freeze({
    family: 'garage-rock-riff', preserveSectionOrder: true, harmonyPath: [0,0,3,5,0], swing: 0.02, warmth: 0.66, releaseScale: 0.88, space: 0.045, delayMs: 85,
    chordInstrument: 'guitar2', bassInstrument: 'bass', chordHoldSteps: 8, bassHoldSteps: 3,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: false }, mix: { lead: 0.82, counter: 0, bass: 1.05, chord: 0.42 },
    percussion: { period: 12, kit: 'legacy', punch: 1.26, pattern: {0:'K',3:'H',6:'S',9:'H'} },
  }),
  desertDriveRock: Object.freeze({
    family: 'desert-road-rock', preserveSectionOrder: true, harmonyPath: [0,0,-2,5,0], swing: 0.08, warmth: 0.82, releaseScale: 1.05, space: 0.10, delayMs: 145,
    chordInstrument: 'tremolo', bassInstrument: 'uprightBass', chordHoldSteps: 16, bassHoldSteps: 4,
    layers: { lead: true, counter: true, chords: true, bass: true, drums: true, signature: false }, mix: { lead: 0.70, counter: 0.40, bass: 0.94, chord: 0.34 },
    percussion: { period: 12, kit: 'legacy', punch: 1.08, pattern: {0:'K',3:'H',6:'S',9:'H'} },
  }),
  endgameAdagio: Object.freeze({
    family: 'chamber-adagio', preserveSectionOrder: true, harmonyPath: [0,0,-2,0,5,0], swing: 0, warmth: 0.92, releaseScale: 1.72, space: 0.28, delayMs: 310,
    chordInstrument: 'strings', bassInstrument: 'cello', chordHoldSteps: 24, bassHoldSteps: 20, drumMode: 'none',
    layers: { lead: true, counter: true, chords: true, bass: true, drums: false, signature: false }, mix: { lead: 0.52, counter: 0.28, bass: 0.42, chord: 0.46 },
    percussion: { period: 32, kit: 'none', punch: 0, pattern: {} },
  }),
  knightFugue: Object.freeze({
    family: 'baroque-fugue', preserveSectionOrder: true, harmonyPath: [0,5,0,7,0,5], swing: 0, warmth: 0.78, releaseScale: 0.84, space: 0.07, delayMs: 90,
    chordInstrument: 'harpsichord', bassInstrument: 'cello', chordHoldSteps: 8, bassHoldSteps: 8, drumMode: 'none',
    layers: { lead: true, counter: true, chords: true, bass: true, drums: false, signature: false }, mix: { lead: 0.68, counter: 0.54, bass: 0.48, chord: 0.34 },
    percussion: { period: 32, kit: 'none', punch: 0, pattern: {} },
  }),
  nocturnalQuartet: Object.freeze({
    family: 'night-string-quartet', preserveSectionOrder: true, harmonyPath: [0,0,3,0,-2,0], swing: 0, warmth: 0.88, releaseScale: 1.58, space: 0.24, delayMs: 270,
    chordInstrument: 'strings', bassInstrument: 'cello', chordHoldSteps: 20, bassHoldSteps: 18, drumMode: 'none',
    layers: { lead: true, counter: true, chords: true, bass: true, drums: false, signature: false }, mix: { lead: 0.50, counter: 0.42, bass: 0.46, chord: 0.38 },
    percussion: { period: 40, kit: 'none', punch: 0, pattern: {} },
  }),
  lofiRainTape: Object.freeze({
    family:'lofi-rain-cassette', preserveSectionOrder:true, harmonyPath:[0,0,-2,0,3,0], swing:.18, warmth:1.08, releaseScale:1.28, space:.11, delayMs:145,
    chordInstrument:'epiano', bassInstrument:'uprightBass', chordHoldSteps:14, bassHoldSteps:4.5,
    layers:{lead:true,counter:true,chords:true,bass:true,drums:true,signature:false}, mix:{lead:.46,counter:.32,bass:.82,chord:.52},
    percussion:{period:16,kit:'lofi',punch:.62,pattern:{0:'B',8:'H'}},
  }),
  lofiWindowLight: Object.freeze({
    family:'lofi-window-vibes', preserveSectionOrder:true, harmonyPath:[0,0,5,0,-2,0], swing:.13, warmth:1.02, releaseScale:1.36, space:.15, delayMs:175,
    chordInstrument:'rhodesWarm', bassInstrument:'uprightBass', chordHoldSteps:16, bassHoldSteps:5,
    layers:{lead:true,counter:true,chords:true,bass:true,drums:true,signature:false}, mix:{lead:.50,counter:.28,bass:.78,chord:.48},
    percussion:{period:16,kit:'lofi',punch:.56,pattern:{0:'B',12:'H'}},
  }),
  neonKnight: Object.freeze({
    family:'neon-synthwave-arp', preserveSectionOrder:true, harmonyPath:[0,0,3,5,0,-2], swing:0, warmth:.64, releaseScale:1.02, space:.13, delayMs:155,
    chordInstrument:'pad', bassInstrument:'synthbass', chordHoldSteps:16, bassHoldSteps:2.4,
    layers:{lead:true,counter:true,chords:true,bass:true,drums:true,signature:false}, mix:{lead:.56,counter:.48,bass:1.12,chord:.42},
    percussion:{period:16,kit:'legacy',punch:1.02,pattern:{0:'K',4:'H',8:'S',12:'H'}},
  }),
  midnightArcade: Object.freeze({
    family:'midnight-arcade-pulse', preserveSectionOrder:true, harmonyPath:[0,0,-1,0,2,0], swing:0, warmth:.52, releaseScale:.76, space:.08, delayMs:95,
    chordInstrument:'synth', bassInstrument:'synthbass', chordHoldSteps:12, bassHoldSteps:2,
    layers:{lead:true,counter:true,chords:true,bass:true,drums:true,signature:false}, mix:{lead:.58,counter:.30,bass:1.18,chord:.34},
    percussion:{period:16,kit:'legacy',punch:1.16,pattern:{0:'K',4:'H',8:'S',12:'H'}},
  }),
});

const EXTRA_STRUCTURED_FEELS = Object.freeze({
  nocturne: Object.freeze({
    family: 'white-nocturne-felt', preserveSectionOrder: true, harmonyPath: [0,0,-2,0], swing: 0, warmth: 0.94, releaseScale: 1.44, space: 0.20, delayMs: 230,
    chordInstrument: 'felt', bassInstrument: 'cello', chordHoldSteps: 18, bassHoldSteps: 12, drumMode: 'none',
    layers: { lead: true, counter: false, chords: true, bass: true, drums: false, signature: true }, mix: { lead: 0.48, counter: 0, bass: 0.42, chord: 0.40 },
    percussion: { period: 32, kit: 'none', punch: 0, pattern: {} },
    signature: { instrument: 'felt', sections: [0,1], everyCycles: 2, repeatPeriod: 64, durationSteps: 7.2, volume: 0.22, motif: {12:72,44:69} },
  }),
  gambit: Object.freeze({
    family: 'royal-gambit-baroque', preserveSectionOrder: true, harmonyPath: [0,5,0,7], swing: 0, warmth: 0.78, releaseScale: 0.86, space: 0.07, delayMs: 92,
    chordInstrument: 'harpsichord', bassInstrument: 'pizz', chordHoldSteps: 8, bassHoldSteps: 4,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.70, counter: 0, bass: 0.52, chord: 0.42 },
    percussion: { period: 16, kit: 'legacy', punch: 0.46, pattern: {0:'W',8:'W'} },
    signature: { instrument: 'harpsichord', sections: [0], everyCycles: 1, repeatPeriod: 32, durationSteps: 4.2, volume: 0.34, motif: {1:76,9:81,17:77,25:83} },
  }),
  casablanca: Object.freeze({
    family: 'midnight-club-vibes', preserveSectionOrder: true, harmonyPath: [0,-2,0,5], swing: 0.12, warmth: 0.78, releaseScale: 1.18, space: 0.19, delayMs: 210,
    chordInstrument: 'epiano', bassInstrument: 'uprightBass', chordHoldSteps: 14, bassHoldSteps: 4,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.54, counter: 0, bass: 1.02, chord: 0.70 },
    percussion: { period: 16, kit: 'brush-jazz', punch: 0.84, pattern: {0:'B',8:'H'} },
    signature: { instrument: 'mutedHorn', sections: [0], everyCycles: 2, repeatPeriod: 32, durationSteps: 6, volume: 0.24, motif: {6:70,22:67} },
  }),
  march: Object.freeze({
    family: 'siege-brass-march', preserveSectionOrder: true, harmonyPath: [0,0,-2,0], swing: 0, warmth: 0.72, releaseScale: 1.02, space: 0.08, delayMs: 110,
    chordInstrument: 'brass', bassInstrument: 'bass', chordHoldSteps: 16, bassHoldSteps: 8,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.76, counter: 0, bass: 0.92, chord: 0.52 },
    percussion: { period: 16, kit: 'legacy', punch: 1.18, pattern: {0:'K',4:'S',8:'K',12:'S'} },
    signature: { instrument: 'brass', sections: [0], everyCycles: 1, repeatPeriod: 32, durationSteps: 5, volume: 0.30, motif: {4:55,20:62} },
  }),
  clockwork: Object.freeze({
    family: 'mechanical-clockwork', preserveSectionOrder: true, harmonyPath: [0,0,2,0,-2,0], swing: 0, warmth: 0.72, releaseScale: 1.0, space: 0.06, delayMs: 72,
    chordInstrument: 'felt', bassInstrument: 'pizz', chordHoldSteps: 8, bassHoldSteps: 6,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.50, counter: 0, bass: 0.46, chord: 0.30 },
    percussion: { period: 16, kit: 'legacy', punch: 0.34, pattern: {0:'W',4:'W',8:'W',12:'W'} },
    signature: { instrument: 'metallic', sections: [0], everyCycles: 2, repeatPeriod: 32, durationSteps: 3, volume: 0.18, motif: {3:76,11:74,19:71,27:69} },
  }),
  velvet: Object.freeze({
    family: 'steel-velvet-noir', preserveSectionOrder: true, harmonyPath: [0,0,-2,0,5,0], swing: 0.08, warmth: 0.84, releaseScale: 1.32, space: 0.18, delayMs: 190,
    chordInstrument: 'rhodesWarm', bassInstrument: 'cello', chordHoldSteps: 16, bassHoldSteps: 8,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.52, counter: 0, bass: 0.54, chord: 0.62 },
    percussion: { period: 16, kit: 'brush-jazz', punch: 0.54, pattern: {6:'B',14:'B'} },
    signature: { instrument: 'vibes', sections: [0], everyCycles: 2, repeatPeriod: 32, durationSteps: 5.5, volume: 0.24, motif: {10:79,26:74} },
  }),
  electricDesert: Object.freeze({
    family: 'electric-desert-driver', preserveSectionOrder: true, harmonyPath: [0,0,3,0,-2,0], swing: 0, warmth: 0.66, releaseScale: 0.96, space: 0.09, delayMs: 96,
    chordInstrument: 'pad', bassInstrument: 'synthbass', chordHoldSteps: 16, bassHoldSteps: 4,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.62, counter: 0, bass: 1.02, chord: 0.36 },
    percussion: { period: 16, kit: 'legacy', punch: 1.0, pattern: {0:'K',4:'H',8:'S',12:'H'} },
    signature: { instrument: 'synth', sections: [0], everyCycles: 1, repeatPeriod: 32, durationSteps: 4, volume: 0.24, motif: {6:71,22:72} },
  }),
  cathedral: Object.freeze({
    family: 'empty-cathedral-organ', preserveSectionOrder: true, harmonyPath: [0,0,-2,0], swing: 0, warmth: 0.9, releaseScale: 1.86, space: 0.34, delayMs: 390,
    chordInstrument: 'organ', bassInstrument: 'organbass', chordHoldSteps: 32, bassHoldSteps: 16, drumMode: 'none',
    layers: { lead: true, counter: false, chords: true, bass: true, drums: false, signature: true }, mix: { lead: 0.34, counter: 0, bass: 0.40, chord: 0.54 },
    percussion: { period: 32, kit: 'none', punch: 0, pattern: {} },
    signature: { instrument: 'choir', sections: [0,1], everyCycles: 2, repeatPeriod: 64, durationSteps: 11, volume: 0.18, motif: {14:67,46:65} },
  }),
  duel: Object.freeze({
    family: 'western-dawn-duel', preserveSectionOrder: true, harmonyPath: [0,0,-2,0], swing: 0.04, warmth: 0.82, releaseScale: 1.0, space: 0.1, delayMs: 124,
    chordInstrument: 'guitar2', bassInstrument: 'bass', chordHoldSteps: 16, bassHoldSteps: 8,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.54, counter: 0, bass: 0.66, chord: 0.36 },
    percussion: { period: 32, kit: 'legacy', punch: 0.34, pattern: {0:'W',16:'W',24:'W'} },
    signature: { instrument: 'mutedHorn', sections: [0], everyCycles: 2, repeatPeriod: 32, durationSteps: 5.2, volume: 0.18, motif: {7:67,23:64} },
  }),
  storm: Object.freeze({
    family: 'tactical-storm-arp', preserveSectionOrder: true, harmonyPath: [0,1,0,-1], swing: 0, warmth: 0.58, releaseScale: 0.82, space: 0.05, delayMs: 78,
    chordInstrument: 'pad', bassInstrument: 'synthbass', chordHoldSteps: 16, bassHoldSteps: 2,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.68, counter: 0, bass: 1.0, chord: 0.26 },
    percussion: { period: 8, kit: 'legacy', punch: 1.18, pattern: {0:'K',2:'H',4:'S',6:'H'} },
    signature: { instrument: 'synth', sections: [0], everyCycles: 1, repeatPeriod: 32, durationSteps: 3, volume: 0.18, motif: {1:74,17:75} },
  }),
  lateEndgame: Object.freeze({
    family: 'late-endgame-felt', preserveSectionOrder: true, harmonyPath: [0,0,-2,0], swing: 0, warmth: 0.82, releaseScale: 1.62, space: 0.26, delayMs: 315,
    chordInstrument: 'felt', bassInstrument: 'cello', chordHoldSteps: 16, bassHoldSteps: 16, drumMode: 'none',
    layers: { lead: true, counter: false, chords: true, bass: true, drums: false, signature: true }, mix: { lead: 0.50, counter: 0, bass: 0.42, chord: 0.40 },
    percussion: { period: 32, kit: 'none', punch: 0, pattern: {} },
    signature: { instrument: 'felt', sections: [0,1], everyCycles: 2, repeatPeriod: 64, durationSteps: 6.5, volume: 0.18, motif: {20:69,52:67} },
  }),
  rigaRain: Object.freeze({
    family: 'riga-rain-marimba', preserveSectionOrder: true, harmonyPath: [0,0,-2,0,3,0], swing: 0.12, warmth: 0.96, releaseScale: 1.14, space: 0.14, delayMs: 145,
    chordInstrument: 'felt', bassInstrument: 'pizz', chordHoldSteps: 16, bassHoldSteps: 8,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.54, counter: 0, bass: 0.44, chord: 0.26 },
    percussion: { period: 16, kit: 'brush-jazz', punch: 0.42, pattern: {7:'B',15:'B'} },
    signature: { instrument: 'marimba', sections: [0,1], everyCycles: 2, repeatPeriod: 32, durationSteps: 4.8, volume: 0.22, motif: {5:70,21:69} },
  }),
  kingTango: Object.freeze({
    family: 'knife-king-tango', preserveSectionOrder: true, harmonyPath: [0,-2,0,-2], swing: 0, warmth: 0.76, releaseScale: 0.94, space: 0.07, delayMs: 98,
    chordInstrument: 'bandoneon', bassInstrument: 'bass', chordHoldSteps: 8, bassHoldSteps: 3,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.72, counter: 0, bass: 1.0, chord: 0.44 },
    percussion: { period: 8, kit: 'legacy', punch: 1.0, pattern: {0:'K',3:'W',4:'K',7:'S'} },
    signature: { instrument: 'bandoneon', sections: [0], everyCycles: 2, repeatPeriod: 32, durationSteps: 4.8, volume: 0.26, motif: {11:76,27:65} },
  }),
  orbitalMonastery: Object.freeze({
    family: 'orbital-monastery-choir', preserveSectionOrder: true, harmonyPath: [0,0,5,0], swing: 0, warmth: 0.9, releaseScale: 1.9, space: 0.38, delayMs: 420,
    chordInstrument: 'pad', bassInstrument: 'organbass', chordHoldSteps: 32, bassHoldSteps: 16, drumMode: 'none',
    layers: { lead: true, counter: false, chords: true, bass: true, drums: false, signature: true }, mix: { lead: 0.36, counter: 0, bass: 0.38, chord: 0.46 },
    percussion: { period: 32, kit: 'none', punch: 0, pattern: {} },
    signature: { instrument: 'choir', sections: [0,1], everyCycles: 2, repeatPeriod: 64, durationSteps: 12, volume: 0.2, motif: {12:72,44:69} },
  }),
  metro317: Object.freeze({
    family: 'metro-fluorescent-pulse', preserveSectionOrder: true, harmonyPath: [0,0,-1,0], swing: 0.04, warmth: 0.56, releaseScale: 0.78, space: 0.04, delayMs: 78,
    chordInstrument: 'synth', bassInstrument: 'synthbass', chordHoldSteps: 16, bassHoldSteps: 2,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.62, counter: 0, bass: 1.08, chord: 0.28 },
    percussion: { period: 16, kit: 'legacy', punch: 1.06, pattern: {0:'K',2:'H',6:'S',10:'K',14:'S'} },
    signature: { instrument: 'pulse', sections: [0], everyCycles: 1, repeatPeriod: 32, durationSteps: 2.5, volume: 0.18, motif: {3:67,19:67} },
  }),
  glassAsh: Object.freeze({
    family: 'glass-ash-static', preserveSectionOrder: true, harmonyPath: [0,0,-2,-2], swing: 0, warmth: 0.8, releaseScale: 1.56, space: 0.28, delayMs: 330,
    chordInstrument: 'pad', bassInstrument: 'cello', chordHoldSteps: 20, bassHoldSteps: 16, drumMode: 'none',
    layers: { lead: true, counter: false, chords: true, bass: true, drums: false, signature: true }, mix: { lead: 0.34, counter: 0, bass: 0.40, chord: 0.28 },
    percussion: { period: 32, kit: 'none', punch: 0, pattern: {} },
    signature: { instrument: 'felt', sections: [0,1], everyCycles: 2, repeatPeriod: 64, durationSteps: 7.5, volume: 0.14, motif: {9:72,41:69} },
  }),
  machineRoom: Object.freeze({
    family: 'machine-room-industrial', preserveSectionOrder: true, harmonyPath: [0,0,1,0,-1,0], swing: 0, warmth: 0.54, releaseScale: 0.82, space: 0.03, delayMs: 70,
    chordInstrument: 'pad', bassInstrument: 'synthbass', chordHoldSteps: 16, bassHoldSteps: 2,
    layers: { lead: true, counter: false, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.52, counter: 0, bass: 1.12, chord: 0.22 },
    percussion: { period: 16, kit: 'legacy', punch: 1.14, pattern: {0:'M',4:'K',8:'M',12:'S'} },
    signature: { instrument: 'metallic', sections: [0], everyCycles: 1, repeatPeriod: 32, durationSteps: 2.4, volume: 0.16, motif: {6:59,22:55} },
  }),
  terraceFireflies: Object.freeze({
    family: 'terrace-fireflies-jazz', preserveSectionOrder: true, harmonyPath: [0,0,5,0,-2,0], swing: 0.18, warmth: 0.92, releaseScale: 1.24, space: 0.15, delayMs: 165,
    chordInstrument: 'epiano', bassInstrument: 'uprightBass', chordHoldSteps: 14, bassHoldSteps: 4,
    layers: { lead: true, counter: true, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.56, counter: 0.36, bass: 0.90, chord: 0.56 },
    percussion: { period: 16, kit: 'brush-jazz', punch: 0.76, pattern: {0:'B',8:'H'} },
    signature: { instrument: 'clarinet', sections: [0,1,2,3], everyCycles: 2, repeatPeriod: 32, durationSteps: 5.4, volume: 0.20, motif: {6:79,22:77} },
  }),
  cafeFirelight: Object.freeze({
    family: 'cafe-firelight-jazz', preserveSectionOrder: true, harmonyPath: [0,-2,0,5,0], swing: 0.14, warmth: 0.86, releaseScale: 1.12, space: 0.14, delayMs: 155,
    chordInstrument: 'epiano', bassInstrument: 'bass', chordHoldSteps: 14, bassHoldSteps: 4,
    layers: { lead: true, counter: true, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.52, counter: 0.28, bass: 0.92, chord: 0.58 },
    percussion: { period: 16, kit: 'brush-jazz', punch: 0.78, pattern: {0:'B',8:'H'} },
    signature: { instrument: 'mutedHorn', sections: [0,1,2,3], everyCycles: 2, repeatPeriod: 32, durationSteps: 5.8, volume: 0.22, motif: {4:68,20:65} },
  }),
  malagaLastTram: Object.freeze({
    family: 'malaga-last-tram-jazz', preserveSectionOrder: true, harmonyPath: [0,0,5,0,-2,0], swing: 0.12, warmth: 0.9, releaseScale: 1.16, space: 0.15, delayMs: 150,
    chordInstrument: 'epiano', bassInstrument: 'bass', chordHoldSteps: 14, bassHoldSteps: 4,
    layers: { lead: true, counter: true, chords: true, bass: true, drums: true, signature: true }, mix: { lead: 0.56, counter: 0.32, bass: 0.92, chord: 0.52 },
    percussion: { period: 16, kit: 'rooftop-jazz', punch: 0.86, pattern: {0:'B',8:'H'} },
    signature: { instrument: 'guitar2', sections: [0,1,2,3], everyCycles: 2, repeatPeriod: 32, durationSteps: 4.8, volume: 0.18, motif: {5:67,21:64} },
  }),
});


const V166BT_STRUCTURED_FEELS = Object.freeze({
  neonSiege: Object.freeze({
    family:'synth-metal-neon-siege', preserveSectionOrder:true, harmonyPath:[0,0,-2,0,3,0], swing:0, warmth:.48, releaseScale:.68, space:.05, delayMs:68,
    leadInstrument:'guitar2', counterInstrument:'arp', chordInstrument:'synth', bassInstrument:'synthbass', chordHoldSteps:8, bassHoldSteps:1.7,
    layers:{lead:true,counter:true,chords:true,bass:true,drums:true,signature:false}, mix:{lead:.74,counter:.40,bass:1.18,chord:.30},
    percussion:{period:16,kit:'synth-metal-thrash',punch:1.48,pattern:{0:'K',1:'H',2:'K',3:'H',4:'K',5:'H',6:'K',7:'H',8:'S',9:'H',10:'K',11:'K',12:'K',13:'H',14:'K',15:'H'}},
  }),
  overclockedKnight: Object.freeze({
    family:'synth-metal-overclocked-gallop', preserveSectionOrder:true, harmonyPath:[0,0,3,0,-2,0], swing:0, warmth:.44, releaseScale:.62, space:.04, delayMs:58,
    leadInstrument:'pulse', counterInstrument:'guitar2', chordInstrument:'pad', bassInstrument:'synthbass', chordHoldSteps:8, bassHoldSteps:1.45,
    layers:{lead:true,counter:true,chords:true,bass:true,drums:true,signature:false}, mix:{lead:.62,counter:.66,bass:1.22,chord:.24},
    percussion:{period:12,kit:'synth-metal-gallop',punch:1.34,pattern:{0:'K',2:'H',3:'K',5:'K',6:'S',8:'H',9:'K',11:'K'}},
  }),
  reactorGambit: Object.freeze({
    family:'synth-metal-reactor-half-time', preserveSectionOrder:true, harmonyPath:[0,0,-2,0,5,0], swing:0, warmth:.52, releaseScale:.78, space:.07, delayMs:82,
    leadInstrument:'guitar2', counterInstrument:'synth', chordInstrument:'pad', bassInstrument:'synthbass', chordHoldSteps:12, bassHoldSteps:2,
    layers:{lead:true,counter:true,chords:true,bass:true,drums:true,signature:false}, mix:{lead:.78,counter:.34,bass:1.24,chord:.34},
    percussion:{period:16,kit:'industrial-half-time',punch:1.52,pattern:{0:'K',4:'M',8:'S',12:'K',14:'M'}},
  }),
  concreteRain: Object.freeze({
    family:'concrete-trip-hop-noir', preserveSectionOrder:true, harmonyPath:[0,0,-2,0,-5,0], swing:.08, warmth:.68, releaseScale:1.28, space:.22, delayMs:240,
    leadInstrument:'mutedHorn', counterInstrument:'rhodesWarm', chordInstrument:'epiano', bassInstrument:'synthbass', chordHoldSteps:16, bassHoldSteps:8,
    layers:{lead:true,counter:true,chords:true,bass:true,drums:true,signature:true}, mix:{lead:.48,counter:.30,bass:1.08,chord:.56},
    percussion:{period:16,kit:'brush-jazz',punch:.82,pattern:{0:'K',8:'S',12:'B'}},
    signature:{instrument:'mutedHorn',sections:[0,1],everyCycles:2,repeatPeriod:64,durationSteps:7.2,volume:.18,motif:{14:65,46:62}},
  }),
  velvetStatic: Object.freeze({
    family:'velvet-static-dub', preserveSectionOrder:true, harmonyPath:[0,0,3,0,-2,0], swing:.14, warmth:.86, releaseScale:1.42, space:.28, delayMs:310,
    leadInstrument:'rhodesWarm', counterInstrument:'cello', chordInstrument:'pad', bassInstrument:'uprightBass', chordHoldSteps:20, bassHoldSteps:8,
    layers:{lead:true,counter:true,chords:true,bass:true,drums:true,signature:false}, mix:{lead:.50,counter:.34,bass:.96,chord:.46},
    percussion:{period:16,kit:'brush-jazz',punch:.68,pattern:{0:'K',10:'B',8:'S'}},
  }),
  abyssalArchive: Object.freeze({
    family:'abyssal-organ-archive', preserveSectionOrder:true, harmonyPath:[0,0,-2,-2,0], swing:0, warmth:.78, releaseScale:1.95, space:.42, delayMs:470,
    leadInstrument:'choir', counterInstrument:'cello', chordInstrument:'organ', bassInstrument:'organbass', chordHoldSteps:40, bassHoldSteps:20, drumMode:'none',
    layers:{lead:true,counter:true,chords:true,bass:true,drums:false,signature:true}, mix:{lead:.30,counter:.30,bass:.40,chord:.48},
    percussion:{period:40,kit:'none',punch:0,pattern:{}},
    signature:{instrument:'organ',sections:[0,1,2],everyCycles:2,repeatPeriod:80,durationSteps:14,volume:.14,motif:{18:43,58:40}},
  }),
  redVault: Object.freeze({
    family:'red-vault-strings-drone', preserveSectionOrder:true, harmonyPath:[0,0,1,0,-1,0], swing:0, warmth:.72, releaseScale:1.72, space:.34, delayMs:380,
    leadInstrument:'strings', counterInstrument:'organ', chordInstrument:'pad', bassInstrument:'cello', chordHoldSteps:24, bassHoldSteps:12, drumMode:'none',
    layers:{lead:true,counter:true,chords:true,bass:true,drums:false,signature:true}, mix:{lead:.40,counter:.22,bass:.48,chord:.34},
    percussion:{period:48,kit:'none',punch:0,pattern:{}},
    signature:{instrument:'cello',sections:[0,1],everyCycles:2,repeatPeriod:96,durationSteps:11,volume:.18,motif:{20:38,68:36}},
  }),
  queenBossa: Object.freeze({
    family:'queen-terrace-bossa', preserveSectionOrder:true, harmonyPath:[0,5,0,-2,0,3], swing:.20, warmth:1.02, releaseScale:1.08, space:.11, delayMs:125,
    leadInstrument:'guitar2', counterInstrument:'rhodesWarm', chordInstrument:'epiano', bassInstrument:'uprightBass', chordHoldSteps:16, bassHoldSteps:4,
    layers:{lead:true,counter:true,chords:true,bass:true,drums:true,signature:true}, mix:{lead:.58,counter:.30,bass:.90,chord:.50},
    percussion:{period:16,kit:'brush-jazz',punch:.64,pattern:{0:'B',6:'H',8:'B',14:'H'}},
    signature:{instrument:'guitar2',sections:[0,1],everyCycles:2,repeatPeriod:64,durationSteps:4.2,volume:.18,motif:{10:67,42:64}},
  }),
  havana205: Object.freeze({
    family:'havana-after-hours-lounge', preserveSectionOrder:true, harmonyPath:[0,-2,0,5,0], swing:.10, warmth:.84, releaseScale:1.0, space:.09, delayMs:110,
    leadInstrument:'bandoneon', counterInstrument:'guitar2', chordInstrument:'rhodesWarm', bassInstrument:'bass', chordHoldSteps:16, bassHoldSteps:4,
    layers:{lead:true,counter:true,chords:true,bass:true,drums:true,signature:true}, mix:{lead:.62,counter:.30,bass:.96,chord:.46},
    percussion:{period:16,kit:'andalus-hand',punch:.76,pattern:{0:'K',6:'H',8:'S',14:'H'}},
    signature:{instrument:'bandoneon',sections:[0,1],everyCycles:2,repeatPeriod:64,durationSteps:4.6,volume:.20,motif:{12:69,44:65}},
  }),
  fourSquares: Object.freeze({
    family:'four-squares-minimal-piano', preserveSectionOrder:true, harmonyPath:[0,0,2,0,-2,0], swing:0, warmth:.96, releaseScale:1.60, space:.24, delayMs:290,
    leadInstrument:'felt', counterInstrument:'cello', chordInstrument:'felt', bassInstrument:'cello', chordHoldSteps:24, bassHoldSteps:24, drumMode:'none',
    layers:{lead:true,counter:true,chords:true,bass:true,drums:false,signature:false}, mix:{lead:.48,counter:.26,bass:.34,chord:.36},
    percussion:{period:48,kit:'none',punch:0,pattern:{}},
  }),
  verticalRainPiano: Object.freeze({
    family:'vertical-rain-solo-piano', preserveSectionOrder:true, harmonyPath:[0,0,-2,0], swing:0, warmth:1.04, releaseScale:1.82, space:.30, delayMs:350,
    leadInstrument:'felt', counterInstrument:'cello', chordInstrument:'felt', bassInstrument:'cello', chordHoldSteps:20, bassHoldSteps:20, drumMode:'none',
    layers:{lead:true,counter:true,chords:true,bass:true,drums:false,signature:true}, mix:{lead:.54,counter:.20,bass:.30,chord:.28},
    percussion:{period:40,kit:'none',punch:0,pattern:{}},
    signature:{instrument:'felt',sections:[0,1,2],everyCycles:2,repeatPeriod:80,durationSteps:8,volume:.14,motif:{16:64,56:62}},
  }),
});

const STRUCTURED_FEEL_BY_THEME = Object.freeze({
  zugzwangWaltz: 'zugzwangWaltz', bishopBlues: 'bishopBlues', winterLibrary: 'winterLibrary',
  analogBunker: 'analogBunker', queenRequiem: 'queenRequiem', nightFreight: 'nightFreight',
  mistSpa: 'mistSpa', moonOnsen: 'moonOnsen', postRockMidnight: 'postRockMidnight', rookGarage: 'rookGarage',
  desertDriveRock: 'desertDriveRock', endgameAdagio: 'endgameAdagio', knightFugue: 'knightFugue', nocturnalQuartet: 'nocturnalQuartet',
  lofiRainTape: 'lofiRainTape', lofiWindowLight: 'lofiWindowLight', neonKnight: 'neonKnight', midnightArcade: 'midnightArcade',
  alexandria241: 'alexandriaLounge',
  cairo0047: 'cairoAfterHours', cairoQuietHours: 'cairoQuietNoir', cairoRedLantern: 'cairoAfterHours', nileBalcony0152: 'nileBalconyAir',
  beirut0113: 'beirutSixEight', beirutRooftop0412: 'beirutRooftop', beirutNightTaxi: 'beirutRooftop',
  damascusBlueHour: 'damascusDrone', aleppoAfterRain: 'levantBlue', ammanVelvetRoom: 'levantBlue',
  istanbul0326: 'istanbulBroken', bosphorusRain: 'levantBlue', istanbulBackgammon: 'istanbulBroken',
  tangierSmoke: 'tangierWalking', tangierRedTable: 'tangierWalking', casablancaLastCall: 'maghrebVelvet', medinaBlueSmoke: 'maghrebVelvet',
  andalusianCoast: 'andalusWarm', granadaPatio: 'granadaChamber', cadizLanterns: 'andalusWarm',
  beirutHarbor2340: 'beirutRooftop', cairoBlueNote0211: 'cairoAfterHours', alexandriaHarborCafe: 'alexandriaLounge',
  cordobaRooftop0026: 'andalusWarm', damascusCourtyard0144: 'levantBlue', tangierNightTrain0058: 'tangierWalking',
  granadaCopperRain0232: 'granadaChamber', ammanLateTable0303: 'levantBlue',
});

const EXTRA_STRUCTURED_FEEL_BY_THEME = Object.freeze({
  nocturne: 'nocturne', gambit: 'gambit', casablanca: 'casablanca', march: 'march', clockwork: 'clockwork',
  velvet: 'velvet', electricDesert: 'electricDesert', cathedral: 'cathedral', duel: 'duel', storm: 'storm',
  lateEndgame: 'lateEndgame', rigaRain: 'rigaRain', kingTango: 'kingTango', orbitalMonastery: 'orbitalMonastery',
  metro317: 'metro317', glassAsh: 'glassAsh', machineRoom: 'machineRoom', terraceFireflies: 'terraceFireflies',
  cafeFirelight: 'cafeFirelight', malagaLastTram: 'malagaLastTram',
});


const V166BT_STRUCTURED_FEEL_BY_THEME = Object.freeze({
  neonSiege:'neonSiege', overclockedKnight:'overclockedKnight', reactorGambit:'reactorGambit',
  concreteRain:'concreteRain', velvetStatic:'velvetStatic', abyssalArchive:'abyssalArchive', redVault:'redVault',
  queenBossa:'queenBossa', havana205:'havana205', fourSquares:'fourSquares', verticalRainPiano:'verticalRainPiano',
});

export function structuredFeel(theme) {
  const key = STRUCTURED_FEEL_BY_THEME[theme?.id] || EXTRA_STRUCTURED_FEEL_BY_THEME[theme?.id] || V166BT_STRUCTURED_FEEL_BY_THEME[theme?.id];
  return (key && (STRUCTURED_FEELS[key] || EXTRA_STRUCTURED_FEELS[key] || V166BT_STRUCTURED_FEELS[key])) || null;
}
