// openings-data.js — Las 6 aperturas famosas, antes enterradas como
// lecciones 11-16 dentro del flujo lineal del Tutorial (nadie las
// encontraba ahí). Ahora tienen su propia pantalla, con acceso directo
// desde el menú.

export const OPENING_LESSONS = [
  {
    key: 'apertura-espanola',
    title: 'Apertura Española (Ruy López)',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de rey — la jugada más jugada de la historia del ajedrez, con enorme diferencia.',
      'Las negras responden igual, disputando el centro de forma simétrica.',
      'El caballo sale a atacar el peón de e5, y de paso prepara el enroque corto más adelante.',
      'Las negras defienden ese peón desarrollando su propio caballo.',
      'El alfil se va a b5, presionando al caballo que defiende e5 — nombrada por Ruy López de Segura, un clérigo español del siglo XVI que la analizó a fondo. Sigue siendo una de las aperturas más jugadas en ajedrez de torneo, siglos después.',
    ],
    intro: 'Una de las aperturas más antiguas y más estudiadas que existen — todavía se juega en el más alto nivel.',
  },
  {
    key: 'apertura-italiana',
    title: 'Apertura Italiana',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4'],
    moveNotes: [
      'Otra vez el peón de rey — el punto de partida más común en ajedrez.',
      'Simetría inicial, igual que en la Española.',
      'Desarrollo natural del caballo, atacando e5.',
      'Defensa natural del peón.',
      'El alfil apunta directo al punto más débil del bando negro (f7) en vez de ir a b5 como en la Española — un plan más directo y agresivo, ideal para quien recién empieza a entender el ataque.',
    ],
    intro: 'Junto con la Española, es de las primeras aperturas "clásicas" que se enseñan — desarrollo rápido y planes claros.',
  },
  {
    key: 'apertura-siciliana',
    title: 'Defensa Siciliana (Najdorf)',
    moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6'],
    moveNotes: [
      'Las blancas abren con el peón de rey.',
      'En vez de responder simétrico, las negras juegan al flanco de dama — la respuesta a 1.e4 más jugada en ajedrez de torneo, con diferencia.',
      'Las blancas desarrollan el caballo, preparando el centro.',
      'Las negras refuerzan su propio avance central futuro.',
      'Las blancas abren el centro con d4.',
      'Las negras capturan.',
      'El caballo recaptura, quedando muy activo en el centro.',
      'Las negras desarrollan su caballo, atacando el peón de e4.',
      'Las blancas defienden ese peón desarrollando su propio caballo.',
      'Y aquí llega la Variante Najdorf: este tirón de peón discreto (a6) es una de las líneas más analizadas de toda la teoría de aperturas — la jugó Bobby Fischer y sigue viva hoy en el ajedrez de élite.',
    ],
    intro: 'La Siciliana es asimétrica desde la segunda jugada: las negras renuncian a pelear el centro de igual a igual, a cambio de más actividad más adelante.',
  },
  {
    key: 'gambito-dama',
    title: 'Gambito de Dama',
    moves: ['d4', 'd5', 'c4'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de dama en vez del de rey — la otra gran familia de aperturas, junto a las que empiezan con e4.',
      'Las negras responden igual, disputando el centro.',
      'Un "gambito" es ofrecer material a cambio de otra ventaja (tiempo, espacio, iniciativa) — acá las blancas ofrecen el peón de c4. Si las negras lo capturan, no lo pueden sostener fácilmente, y las blancas recuperan la iniciativa en el centro.',
    ],
    intro: 'Pese al nombre, casi nunca se juega para ganar un peón de verdad — es sobre todo una forma de pelear el centro con más flexibilidad.',
  },
  {
    key: 'india-rey',
    title: 'Defensa India de Rey',
    moves: ['d4', 'Nf6', 'c4', 'g6'],
    moveNotes: [
      'Otra vez el peón de dama.',
      'En vez de disputar el centro con un peón, las negras desarrollan primero una pieza — una idea "moderna" (de principios del siglo XX) frente a las aperturas clásicas.',
      'Las blancas siguen ocupando el centro.',
      'Las negras preparan fianchettar el alfil (llevarlo a la diagonal larga desde g7) en vez de pelear el centro de entrada — dejan que las blancas ocupen el centro para atacarlo después, con más piezas en juego.',
    ],
    intro: 'Un ejemplo de "hipermoderno": ceder el centro a propósito al principio, para presionarlo después en vez de ocuparlo directo.',
  },
  {
    key: 'caro-kann',
    title: 'Defensa Caro-Kann',
    moves: ['e4', 'c6', 'd4', 'd5'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de rey.',
      'Las negras preparan d5 con este peón, sin bloquear la salida de su alfil de casillas claras — a diferencia de la Francesa (e6), que sí lo encierra.',
      'Las blancas amplían el centro.',
      'Las negras golpean ese centro — una defensa sólida, menos combativa que la Siciliana pero con una estructura de peones más fácil de manejar a largo plazo.',
    ],
    intro: 'La otra gran respuesta "sólida" a 1.e4, junto con la Francesa — pero sin encerrar el alfil de casillas claras.',
  },
  {
    key: 'grunfeld',
    title: 'Defensa Grünfeld',
    moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de dama.',
      'Como en la India de Rey, las negras desarrollan una pieza antes que un peón.',
      'Las blancas siguen ocupando el centro.',
      'Las negras preparan fianchettar el alfil, igual que en la India de Rey — hasta acá son la misma apertura.',
      'Las blancas desarrollan el caballo.',
      'Y acá se separa de la India de Rey: en vez de dejar el centro entero a las blancas, las negras lo golpean de entrada con este peón — mucho más afilada y directa que su prima hipermoderna.',
    ],
    intro: 'Nace de la misma familia que la India de Rey (mismas primeras jugadas), pero se vuelve mucho más combativa a partir de la cuarta.',
  },
  {
    key: 'inglesa',
    title: 'Apertura Inglesa',
    moves: ['c4', 'e5', 'Nc3', 'Nf6'],
    moveNotes: [
      'Ni peón de rey ni de dama — las blancas abren por el flanco de dama, la tercera gran familia de aperturas después de 1.e4 y 1.d4.',
      'Las negras responden con el peón de rey, buscando una estructura parecida a una Siciliana con los colores invertidos.',
      'Las blancas desarrollan el caballo, presionando el centro sin comprometerse a una estructura de peones todavía.',
      'Desarrollo natural — la Inglesa suele derivar en posiciones muy flexibles, donde ambos bandos deciden la estructura central bastante más tarde que en 1.e4 o 1.d4.',
    ],
    intro: 'La apertura "flanco" más jugada en ajedrez de élite — pospone la pelea por el centro en vez de entrarle directo.',
  },
  {
    key: 'escocesa',
    title: 'Apertura Escocesa',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de rey.',
      'Simetría inicial, igual que en la Española o la Italiana.',
      'Desarrollo natural del caballo, atacando e5.',
      'Defensa natural del peón.',
      'En vez de desarrollar una pieza (como en la Española o la Italiana), las blancas abren el centro de una — más directa y táctica, cambia estructura por actividad inmediata de las piezas.',
    ],
    intro: 'La tercera gran respuesta a 1...e5 después de la Española y la Italiana — mismo arranque, pero rompe el centro antes en vez de desarrollar primero.',
  },
  {
    key: 'defensa-francesa',
    title: 'Defensa Francesa',
    moves: ['e4', 'e6'],
    moveNotes: [
      'Las blancas abren con el peón de rey.',
      'Las negras preparan d5 en la siguiente jugada, apoyadas por este peón — a cambio, el alfil de casillas claras queda encerrado un buen rato detrás de la cadena de peones.',
    ],
    intro: 'Una defensa sólida y algo cerrada — cambia actividad temprana por una estructura difícil de romper.',
  },
  {
    key: 'alekhine',
    title: 'Defensa Alekhine',
    moves: ['e4', 'Nf6', 'e5', 'Nd5'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de rey.',
      'En vez de disputar el centro con un peón o desarrollar con calma, las negras provocan: este caballo invita a las blancas a seguir avanzando peones para atacarlo.',
      'Las blancas aceptan la invitación, ganando espacio y echando al caballo.',
      'El caballo retrocede, pero las blancas ahora tienen peones avanzados que en el medio juego pueden volverse un blanco — la idea central de la apertura: dejar que el rival se sobreextienda para atacarlo después.',
    ],
    intro: 'Nombrada por Alexander Alekhine, campeón mundial que la puso de moda en los años 20 — provoca a las blancas a avanzar peones de más, para atacarlos más adelante.',
  },
  {
    key: 'escandinava',
    title: 'Defensa Escandinava',
    moves: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de rey.',
      'Las negras responden golpeando ese peón de una, en vez de desarrollar primero.',
      'Las blancas capturan.',
      'Las negras recapturan con la dama — sacarla tan temprano no suele recomendarse (es un blanco fácil), pero acá es parte del plan: no hay otra forma natural de recuperar el peón.',
      'Las blancas desarrollan el caballo atacando la dama, ganando un tiempo — las negras van a tener que mover la dama de nuevo antes de terminar de desarrollar las demás piezas.',
    ],
    intro: 'Directa y algo arriesgada: las negras recuperan el peón con la dama bien temprano, a cambio de ceder tiempo de desarrollo.',
  },
  {
    key: 'nimzoindia',
    title: 'Defensa Nimzoindia',
    moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de dama.',
      'Las negras desarrollan una pieza antes que un peón, igual criterio hipermoderno que la India de Rey y la Grünfeld.',
      'Las blancas siguen ocupando el centro.',
      'Las negras preparan la salida del otro alfil.',
      'Las blancas desarrollan el caballo.',
      'Y acá la idea central: el alfil clava el caballo contra el rey, presionando la estructura de peones de las blancas antes de que terminen de organizarse — una de las defensas hipermodernas más respetadas y jugadas en ajedrez de élite.',
    ],
    intro: 'Nombrada por Aron Nimzowitsch, uno de los padres del hipermodernismo — clava una pieza clave antes de que las blancas terminen de desarrollarse.',
  },
  {
    key: 'gambito-rey',
    title: 'Gambito de Rey',
    moves: ['e4', 'e5', 'f4'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de rey.',
      'Simetría inicial.',
      'Las blancas ofrecen un peón a cambio de abrir líneas rápido hacia el rey negro — el gambito más antiguo y famoso del ajedrez romántico del siglo XIX, cuando se privilegiaba el ataque directo por sobre la solidez.',
    ],
    intro: 'La apertura favorita de la era romántica del ajedrez — sacrificar material a cambio de un ataque veloz, en vez de jugar seguro.',
  },
  {
    key: 'pirc',
    title: 'Defensa Pirc',
    moves: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de rey.',
      'Las negras preparan Nf6 sin bloquear la diagonal del alfil de casillas oscuras — una jugada modesta que deja el centro para después.',
      'Las blancas amplían el centro.',
      'Las negras desarrollan el caballo.',
      'Las blancas desarrollan el otro caballo.',
      'Y las negras preparan fianchettar el alfil — misma idea hipermoderna que la India de Rey (dejar que las blancas ocupen el centro para presionarlo después), pero como respuesta a 1.e4 en vez de 1.d4.',
    ],
    intro: 'La versión de la India de Rey para cuando las blancas abren con el peón de rey en vez del de dama — mismo plan hipermoderno, distinto punto de partida.',
  },
  {
    key: 'holandesa',
    title: 'Defensa Holandesa',
    moves: ['d4', 'f5'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de dama.',
      'En vez de disputar el centro directamente, las negras avanzan el peón de alfil de rey — gana espacio en el flanco de rey y prepara un posible ataque ahí, a cambio de debilitar bastante las casillas alrededor de su propio rey.',
    ],
    intro: 'Una de las respuestas más agresivas y menos comunes contra 1.d4 — cambia seguridad del rey por actividad en el flanco.',
  },
  {
    key: 'cuatro-caballos',
    title: 'Apertura de los Cuatro Caballos',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3', 'Nf6'],
    moveNotes: [
      'Las blancas ocupan el centro con el peón de rey.',
      'Simetría inicial, igual que en la Española o la Italiana.',
      'Desarrollo natural del caballo, atacando e5.',
      'Defensa natural del peón.',
      'Las blancas desarrollan el segundo caballo en vez de una jugada de alfil.',
      'Y las negras hacen lo mismo — los cuatro caballos ya están en juego, de ahí el nombre. Una de las aperturas más antiguas y simétricas del ajedrez clásico, sólida pero considerada algo inofensiva en el más alto nivel.',
    ],
    intro: 'Desarrollo puro y simétrico — los cuatro caballos salen antes que cualquier alfil, la esencia del ajedrez clásico del siglo XIX.',
  },
  {
    key: 'reti',
    title: 'Apertura Réti',
    moves: ['Nf3', 'd5', 'c4'],
    moveNotes: [
      'Las blancas desarrollan el caballo antes que cualquier peón central — no revela todavía qué estructura va a jugar.',
      'Las negras ocupan el centro con el peón de dama, la respuesta más natural.',
      'Y acá aparece la idea: en vez de ocupar el centro con peones propios, las blancas lo presionan desde el flanco — puede transformarse en una Inglesa, un Gambito de Dama, o quedarse como posición propia, según cómo respondan las negras.',
    ],
    intro: 'Nombrada por Richard Réti, otro de los grandes hipermodernos — la máxima flexibilidad de apertura: ni un solo peón central movido en las primeras dos jugadas.',
  },
];
