package residenteval

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"testing"
)

// The corpus is generated by scripts/engine_parity_corpus.py from
// backend-python/chess_ai.py; CI regenerates it with --check so the two
// evaluations cannot drift while both runtimes exist.
type pythonCorpus struct {
	PythonChess string `json:"python_chess"`
	Positions   []struct {
		FEN  string          `json:"fen"`
		Eval json.RawMessage `json:"eval"`
	} `json:"positions"`
}

func decodePythonEval(raw json.RawMessage) (float64, error) {
	var text string
	if err := json.Unmarshal(raw, &text); err == nil {
		switch text {
		case "inf":
			return math.Inf(1), nil
		case "-inf":
			return math.Inf(-1), nil
		}
		return 0, fmt.Errorf("unexpected eval %q", text)
	}
	var value float64
	err := json.Unmarshal(raw, &value)
	return value, err
}

func TestEvaluateFENMatchesPythonCorpus(t *testing.T) {
	data, err := os.ReadFile("testdata/python_eval_corpus.json")
	if err != nil {
		t.Fatal(err)
	}
	var corpus pythonCorpus
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatal(err)
	}
	if len(corpus.Positions) < 1000 {
		t.Fatalf("corpus too small: %d positions", len(corpus.Positions))
	}
	mismatches := 0
	for _, position := range corpus.Positions {
		want, err := decodePythonEval(position.Eval)
		if err != nil {
			t.Fatalf("%s: %v", position.FEN, err)
		}
		got, err := EvaluateFEN(position.FEN)
		if err != nil {
			t.Errorf("%s: %v", position.FEN, err)
			continue
		}
		if !sameEval(got, want) {
			mismatches++
			if mismatches <= 20 {
				t.Errorf("%s: go=%v python=%v", position.FEN, got, want)
			}
		}
	}
	if mismatches > 0 {
		t.Fatalf("%d/%d positions differ from Python (python-chess %s)", mismatches, len(corpus.Positions), corpus.PythonChess)
	}
}

func sameEval(a, b float64) bool {
	if math.IsInf(a, 0) || math.IsInf(b, 0) {
		return a == b
	}
	return math.Abs(a-b) <= 1e-9*math.Max(1, math.Abs(b))
}
