package residentpolicy

import (
	"encoding/json"
	"math"
	"os"
	"testing"
)

// The corpus is generated by scripts/cpu_policy_parity_corpus.py from
// backend-python/cpu_difficulty.py, the Python authority for Matthias'
// human-Elo policy in games against the CPU.
type policyCorpus struct {
	Complexities []float64 `json:"complexities"`
	Bands        []struct {
		Level                 float64   `json:"level"`
		Elo                   int       `json:"elo"`
		TargetElo             int       `json:"targetElo"`
		MaxLossCP             float64   `json:"maxLossCP"`
		MistakeChance         float64   `json:"mistakeChance"`
		CandidateLimit        int       `json:"candidateLimit"`
		MaxDepth              int       `json:"maxDepth"`
		BudgetSeconds         float64   `json:"budgetSeconds"`
		SettingsMaxDepth      int       `json:"settingsMaxDepth"`
		SettingsBudgetSeconds float64   `json:"settingsBudgetSeconds"`
		LossCaps              []float64 `json:"lossCaps"`
		MistakeChances        []float64 `json:"mistakeChances"`
	} `json:"bands"`
	Weights []struct {
		Level        float64   `json:"level"`
		Best         float64   `json:"best"`
		Alternatives []float64 `json:"alternatives"`
		Maximizing   bool      `json:"maximizing"`
		Complexity   float64   `json:"complexity"`
		Losses       []float64 `json:"losses"`
		Weights      []float64 `json:"weights"`
	} `json:"weights"`
}

func loadPolicyCorpus(t *testing.T) policyCorpus {
	t.Helper()
	raw, err := os.ReadFile("testdata/python_cpu_policy_corpus.json")
	if err != nil {
		t.Fatal(err)
	}
	var corpus policyCorpus
	if err := json.Unmarshal(raw, &corpus); err != nil {
		t.Fatal(err)
	}
	if len(corpus.Bands) < 101 || len(corpus.Weights) == 0 {
		t.Fatalf("corpus too small: %d bands, %d weights", len(corpus.Bands), len(corpus.Weights))
	}
	return corpus
}

func near(got, want float64) bool {
	return math.Abs(got-want) <= 1e-9*math.Max(1, math.Abs(want))
}

func TestDifficultyBandsMatchPythonCorpus(t *testing.T) {
	corpus := loadPolicyCorpus(t)
	for _, row := range corpus.Bands {
		band := Band(row.Level)
		if got := EloForLevel(row.Level); got != row.Elo {
			t.Errorf("level %v: elo %d, python %d", row.Level, got, row.Elo)
		}
		if band.TargetElo != row.TargetElo || band.CandidateLimit != row.CandidateLimit || band.MaxDepth != row.MaxDepth {
			t.Errorf("level %v: band %#v, python %+v", row.Level, band, row)
		}
		if !near(band.MaxLossCP, row.MaxLossCP) || !near(band.MistakeChance, row.MistakeChance) || !near(band.BudgetSeconds, row.BudgetSeconds) {
			t.Errorf("level %v: band %#v, python %+v", row.Level, band, row)
		}
		depth, budget := SearchSettings(row.Level)
		if depth != row.SettingsMaxDepth || !near(budget, row.SettingsBudgetSeconds) {
			t.Errorf("level %v: settings (%d, %v), python (%d, %v)", row.Level, depth, budget, row.SettingsMaxDepth, row.SettingsBudgetSeconds)
		}
		for i, complexity := range corpus.Complexities {
			if got := EffectiveLossCap(band, complexity); !near(got, row.LossCaps[i]) {
				t.Errorf("level %v complexity %v: loss cap %v, python %v", row.Level, complexity, got, row.LossCaps[i])
			}
			if got := EffectiveMistakeChance(band, complexity); !near(got, row.MistakeChances[i]) {
				t.Errorf("level %v complexity %v: mistake %v, python %v", row.Level, complexity, got, row.MistakeChances[i])
			}
		}
	}
}

func TestCandidateWeightsMatchPythonCorpus(t *testing.T) {
	corpus := loadPolicyCorpus(t)
	for _, row := range corpus.Weights {
		band := Band(row.Level)
		weights := ImperfectCandidateWeights(row.Best, row.Alternatives, row.Maximizing, band, row.Complexity)
		if len(weights) != len(row.Weights) {
			t.Fatalf("%+v: %d weights", row, len(weights))
		}
		for i := range weights {
			if !near(weights[i], row.Weights[i]) {
				t.Errorf("level %v best %v maximizing %v complexity %v: weight[%d] %v, python %v",
					row.Level, row.Best, row.Maximizing, row.Complexity, i, weights[i], row.Weights[i])
			}
			if got := LossFromBest(row.Best, row.Alternatives[i], row.Maximizing); !near(got, row.Losses[i]) {
				t.Errorf("loss[%d] %v, python %v", i, got, row.Losses[i])
			}
		}
	}
}
